#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Deutschland mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape  ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number) {
    #(wd:Q183 "Deutschland" "deutschland" "") 
		(wd:Q985 "Baden-Württemberg" "deutschland/baden-wuerttemberg" "4132")
		(wd:Q980 "Bayern" "deutschland/bayern" "3675")
		(wd:Q64 "Berlin" "deutschland/berlin" "10459")
		(wd:Q1208 "Brandenburg" "deutschland/brandenburg" "343")
		(wd:Q1209 "Bremen" "deutschland/bremen" "954")
		(wd:Q1055 "Hamburg" "deutschland/hamburg" "7333")
		(wd:Q1199 "Hessen" "deutschland/hessen" "7207")
		(wd:Q1196 "Mecklenburg-Vorpommern" "deutschland/mecklenburg-vorpommern" "253")
		(wd:Q1197 "Niedersachsen" "deutschland/niedersachsen" "4128")
		(wd:Q1198 "Nordrhein-Westfalen" "deutschland/nordrhein-westfalen" "2359")
		(wd:Q1200 "Rheinland-Pfalz" "deutschland/rheinland-pfalz" "275")
		(wd:Q1201 "Saarland" "deutschland/saarland" "62")
		(wd:Q1202 "Sachsen" "deutschland/sachsen" "2233")
		(wd:Q1206 "Sachsen-Anhalt" "deutschland/sachsen-anhalt" "1107")
		(wd:Q1194 "Schleswig-Holstein" "deutschland/schleswig-holstein" "868")
		(wd:Q1205 "Thüringen" "deutschland/thueringen" "372")
		}
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label {
	bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" .
  }
}
