#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Hessen mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape  ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number) {
    (wd:Q1199 "Hessen" "deutschland/hessen" "")
        (wd:Q7917 "Landkreis Bergstraße" "deutschland/hessen/landkreis-bergstraße" "")
        (wd:Q7916 "Landkreis Darmstadt-Dieburg" "deutschland/hessen/landkreis-darmstadt-dieburg" "")
        (wd:Q2973 "Darmstadt" "deutschland/hessen/darmstadt" "")
        (wd:Q1794 "Frankfurt am Main" "deutschland/hessen/frankfurt-am-main" "")
        (wd:Q7899 "Landkreis Fulda" "deutschland/hessen/landkreis-fulda" "")
        (wd:Q7904 "Landkreis Gießen" "deutschland/hessen/landkreis-giessen" "")
        (wd:Q7914 "Landkreis Groß-Gerau" "deutschland/hessen/landkreis-gross-gerau" "")
        (wd:Q7898 "Landkreis Hersfeld-Rotenburg" "deutschland/hessen/landkreis-hersfeld-rotenburg" "")
        (wd:Q7908 "Hochtaunuskreis" "deutschland/hessen/hochtaunuskreis" "")
        (wd:Q7890 "Landkreis Kassel" "deutschland/hessen/landkreis-kassel" "")
        (wd:Q2865 "Kassel" "deutschland/hessen/kassel" "")
        (wd:Q7905 "Lahn-Dill-Kreis" "deutschland/hessen/lahn-dill-kreis" "")
        (wd:Q7906 "Landkreis Limburg-Weilburg" "deutschland/hessen/landkreis-limburg-weilburg" "")
        (wd:Q7911 "Main-Kinzig-Kreis" "deutschland/hessen/main-kinzig-kreis" "")
        (wd:Q7909 "Main-Taunus-Kreis" "deutschland/hessen/main-taunus-kreis" "")
        (wd:Q7902 "Landkreis Marburg-Biedenkopf" "deutschland/hessen/landkreis-marburg-biedenkopf" "")
        (wd:Q7919 "Odenwaldkreis" "deutschland/hessen/odenwaldkreis" "")
        (wd:Q7912 "Landkreis Offenbach" "deutschland/hessen/landkreis-offenbach" "")
        (wd:Q3042 "Offenbach am Main" "deutschland/hessen/offenbach-am-main" "")
        (wd:Q7907 "Rheingau-Taunus-Kreis" "deutschland/hessen/rheingau-taunus-kreis" "")
        (wd:Q7894 "Schwalm-Eder-Kreis" "deutschland/hessen/schwalm-eder-kreis" "")
        (wd:Q7901 "Vogelsbergkreis" "deutschland/hessen/vogelsbergkreis" "")
        (wd:Q7893 "Landkreis Waldeck-Frankenberg" "deutschland/hessen/landkreis-waldeck-frankenberg" "")
        (wd:Q7896 "Werra-Meißner-Kreis" "deutschland/hessen/werra-meissner-kreis" "")
        (wd:Q7910 "Wetteraukreis" "deutschland/hessen/wetteraukreis" "")
        (wd:Q1721 "Wiesbaden" "deutschland/hessen/wiesbaden" "")
        }
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label {
	bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" .
  }
}
