#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Landkreise und kreisfreien Städte in Niedersachsen mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape  ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number) {
    # (wd:Q5947 "Landkreis Ammerland" "deutschland/niedersachsen/landkreis-ammerland" "1")
      (wd:Q503471 "Gemeinde Apen" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-apen" "0")
      (wd:Q504526 "Gemeinde Bad Zwischenahn" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-bad-zwischenahn" "0")
      (wd:Q503410 "Gemeinde Edewecht" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-edewecht" "0")
      (wd:Q512640 "Gemeinde Rastede" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-rastede" "0")
      (wd:Q492360 "Westerstede" "deutschland/niedersachsen/landkreis-ammerland/westerstede" "0")
      (wd:Q503388 "Gemeinde Wiefelstede" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-wiefelstede" "1")
    # (wd:Q5929 "Landkreis Aurich" "deutschland/niedersachsen/landkreis-aurich" "8")
      (wd:Q14839 "Aurich" "deutschland/niedersachsen/landkreis-aurich/gemeinde-aurich" "0") 
      (wd:Q25125 "Gemeinde Baltrum" "deutschland/niedersachsen/landkreis-aurich/gemeinde-baltrum" "0") 
      (wd:Q567381 "Gemeinde Dornum" "deutschland/niedersachsen/landkreis-aurich/gemeinde-dornum" "0") 
      (wd:Q302492 "Gemeinde Großefehn" "deutschland/niedersachsen/landkreis-aurich/gemeinde-grossefehn" "0") 
      (wd:Q118862 "Gemeinde Großheide" "deutschland/niedersachsen/landkreis-aurich/gemeinde-grossheide" "0") 
      (wd:Q552451 "Gemeinde Hinte" "deutschland/niedersachsen/landkreis-aurich/gemeinde-hinte" "0") 
      (wd:Q569739 "Gemeinde Ihlow" "deutschland/niedersachsen/landkreis-aurich/gemeinde-ihlow" "0") 
      (wd:Q24846 "Gemeinde Juist" "deutschland/niedersachsen/landkreis-aurich/gemeinde-juist" "0") 
      (wd:Q559432 "Gemeinde Krummhörn" "deutschland/niedersachsen/landkreis-aurich/gemeinde-krummhoern" "0") 
      (wd:Q492366 "Norden" "deutschland/niedersachsen/landkreis-aurich/norden" "0") 
      (wd:Q23968 "Norderney" "deutschland/niedersachsen/landkreis-aurich/norderney" "8") 
      (wd:Q137696 "Gemeinde Südbrookmerland" "deutschland/niedersachsen/landkreis-aurich/gemeinde-suedbrookmerland" "0") 
      (wd:Q511989 "Wiesmoor" "deutschland/niedersachsen/landkreis-aurich/wiesmoor" "0") 
      (wd:Q633537 "Samtgemeinde Brookmerland" "deutschland/niedersachsen/landkreis-aurich/samtgemeinde-brookmerland" "0") 
      (wd:Q519891 "Samtgemeinde Hage" "deutschland/niedersachsen/landkreis-aurich/samtgemeinde-hage" "0") 
    # (wd:Q2773 "Braunschweig" "deutschland/niedersachsen/braunschweig" "414")
        (wd:Q107686879 "Braunschweig-Süd" "deutschland/niedersachsen/braunschweig/braunschweig-sued" "0")
        (wd:Q108043084 "Hondelage-Volkmarode" "deutschland/niedersachsen/braunschweig/hondelage-volkmarode" "0")
        (wd:Q1813224 "Lehndorf-Watenbüttel" "deutschland/niedersachsen/braunschweig/lehndorf-watenbuettel" "0")
        (wd:Q106661169 "Mitte" "deutschland/niedersachsen/braunschweig/mitte" "252")
        (wd:Q108056427 "Nördliche Schunter-/Okeraue" "deutschland/niedersachsen/braunschweig/noerdliche-schunter-okeraue" "0")
        (wd:Q1998672 "Nordstadt-Schunteraue" "deutschland/niedersachsen/braunschweig/nordstadt-schunteraue" "27")
        (wd:Q307301 "Östliches Ringgebiet" "deutschland/niedersachsen/braunschweig/oestliches-ringgebiet" "102")
        (wd:Q2381496 "Südstadt-Rautheim-Mascherode" "deutschland/niedersachsen/braunschweig/suedstadt-rautheim-mascherode" "0")
        (wd:Q106850375 "Südwest" "deutschland/niedersachsen/braunschweig/suedwest" "0")
        (wd:Q2538245 "Wabe-Schunter-Beberbach" "deutschland/niedersachsen/braunschweig/wabe-schunter-beberbach" "0")
        (wd:Q2565488 "Westliches Ringgebiet" "deutschland/niedersachsen/braunschweig/westliches-ringgebiet" "33")
        (wd:Q1363611 "Weststadt" "deutschland/niedersachsen/braunschweig/weststadt" "0")
    # (wd:Q5919 "Landkreis Celle" "deutschland/niedersachsen/landkreis-celle" "115")
      (wd:Q505665 "Bergen" "deutschland/niedersachsen/landkreis-celle/bergen" "0")
      (wd:Q3933 "Celle" "deutschland/niedersachsen/landkreis-celle/celle" "113")
      (wd:Q555622 "Gemeinde Eschede" "deutschland/niedersachsen/landkreis-celle/gemeinde-eschede" "0")
      (wd:Q60569 "Gemeinde Faßberg" "deutschland/niedersachsen/landkreis-celle/gemeinde-fassberg" "0")
      (wd:Q371560 "Gemeinde Hambühren" "deutschland/niedersachsen/landkreis-celle/gemeinde-hambuehren" "0")
      (wd:Q622476 "Bezirk Lohheide" "deutschland/niedersachsen/landkreis-celle/bezirk-lohheide" "0")
      (wd:Q17456671 "Gemeinde Südheide" "deutschland/niedersachsen/landkreis-celle/gemeinde-suedheide" "2")
      (wd:Q574367 "Gemeinde Wietze" "deutschland/niedersachsen/landkreis-celle/gemeinde-wietze" "0")
      (wd:Q622498 "Gemeinde Winsen (Aller)" "deutschland/niedersachsen/landkreis-celle/gemeinde-winsen-aller" "0")
      (wd:Q555806 "Gemeinde Bröckel" "deutschland/niedersachsen/landkreis-celle/gemeinde-broeckel" "0")
      (wd:Q621920 "Gemeinde Eicklingen" "deutschland/niedersachsen/landkreis-celle/gemeinde-eicklingen" "0")
      (wd:Q555820 "Gemeinde Langlingen" "deutschland/niedersachsen/landkreis-celle/gemeinde-langlingen" "0")
      (wd:Q566292 "Gemeinde Wienhausen" "deutschland/niedersachsen/landkreis-celle/gemeinde-wienhausen" "0")
      (wd:Q402327 "Gemeinde Ahnsbeck" "deutschland/niedersachsen/landkreis-celle/gemeinde-ahnsbeck" "0")
      (wd:Q566343 "Gemeinde Beedenbostel" "deutschland/niedersachsen/landkreis-celle/gemeinde-beedenbostel" "0")
      (wd:Q625099 "Gemeinde Eldingen" "deutschland/niedersachsen/landkreis-celle/gemeinde-eldingen" "0")
      (wd:Q566262 "Gemeinde Hohne" "deutschland/niedersachsen/landkreis-celle/gemeinde-hohne" "0")
      (wd:Q566319 "Gemeinde Lachendorf" "deutschland/niedersachsen/landkreis-celle/gemeinde-lachendorf" "0")
      (wd:Q354978 "Gemeinde Adelheidsdorf" "deutschland/niedersachsen/landkreis-celle/gemeinde-adelheidsdorf" "0")
      (wd:Q374704 "Gemeinde Nienhagen" "deutschland/niedersachsen/landkreis-celle/gemeinde-nienhagen" "0")
      (wd:Q566296 "Gemeinde Wathlingen" "deutschland/niedersachsen/landkreis-celle/gemeinde-wathlingen" "0")
    # (wd:Q5945 "Landkreis Cloppenburg" "deutschland/niedersachsen/landkreis-cloppenburg" "41")
      (wd:Q559525 "Gemeinde Barßel" "deutschland/niedersachsen/landkreis-cloppenburg/gemeinde-barssel" "1")
      (wd:Q559590 "Gemeinde Bösel" "deutschland/niedersachsen/landkreis-cloppenburg/gemeinde-boesel" "0")
      (wd:Q559556 "Gemeinde Cappeln" "deutschland/niedersachsen/landkreis-cloppenburg/gemeinde-cappeln" "0")
      (wd:Q16059 "Cloppenburg" "deutschland/niedersachsen/landkreis-cloppenburg/cloppenburg" "38")
      (wd:Q559488 "Gemeinde Emstek" "deutschland/niedersachsen/landkreis-cloppenburg/gemeinde-emstek" "0")
      (wd:Q571423 "Gemeinde Essen (Oldenburg)" "deutschland/niedersachsen/landkreis-cloppenburg/gemeinde-essen-oldenburg" "0")
      (wd:Q559637 "Friesoythe" "deutschland/niedersachsen/landkreis-cloppenburg/friesoythe" "0")
      (wd:Q559605 "Gemeinde Garrel" "deutschland/niedersachsen/landkreis-cloppenburg/gemeinde-garrel" "0")
      (wd:Q559578 "Gemeinde Lastrup" "deutschland/niedersachsen/landkreis-cloppenburg/gemeinde-lastrup" "0")
      (wd:Q559571 "Gemeinde Lindern" "deutschland/niedersachsen/landkreis-cloppenburg/gemeinde-lindern" "0")
      (wd:Q559561 "Löningen" "deutschland/niedersachsen/landkreis-cloppenburg/loeningen" "2")
      (wd:Q559616 "Gemeinde Molbergen" "deutschland/niedersachsen/landkreis-cloppenburg/gemeinde-molbergen" "0")
      (wd:Q27643 "Gemeinde Saterland" "deutschland/niedersachsen/landkreis-cloppenburg/gemeinde-saterland" "0")
    # (wd:Q5897 "Landkreis Cuxhaven" "deutschland/niedersachsen/landkreis-cuxhaven" "51")
      (wd:Q509145 "Gemeinde Beverstedt" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-beverstedt" "9")
      (wd:Q4197 "Cuxhaven" "deutschland/niedersachsen/landkreis-cuxhaven/cuxhaven" "22")
      (wd:Q1497761 "Geestland" "deutschland/niedersachsen/landkreis-cuxhaven/geestland" "0")
      (wd:Q585546 "Gemeinde Hagen im Bremischen" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-hagen-im-bremischen" "2")
      (wd:Q509157 "Gemeinde Loxstedt" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-loxstedt" "13")
      (wd:Q505594 "Gemeinde Schiffdorf" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-schiffdorf" "0")
      (wd:Q2595304 "Gemeinde Wurster Nordseeküste" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-wurster-nordseekueste" "0")
      (wd:Q256680 "Gemeinde Armstorf" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-armstorf" "0")
      (wd:Q509305 "Gemeinde Hollnseth" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-hollnseth" "0")
      (wd:Q503261 "Gemeinde Lamstedt" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-lamstedt" "0")
      (wd:Q509114 "Gemeinde Mittelstenahe" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-mittelstenahe" "0")
      (wd:Q500537 "Gemeinde Stinstedt" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-stinstedt" "0")
      (wd:Q687692 "Gemeinde Hechthausen" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-hechthausen" "0")
      (wd:Q505729 "Hemmoor" "deutschland/niedersachsen/landkreis-cuxhaven/hemmoor" "0")
      (wd:Q509069 "Gemeinde Osten" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-osten" "4")
      (wd:Q509173 "Gemeinde Belum" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-belum" "0")
      (wd:Q509267 "Gemeinde Bülkau" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-buelkau" "0")
      (wd:Q503692 "Gemeinde Cadenberge" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-cadenberge" "0")
      (wd:Q621225 "Gemeinde Ihlienworth" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-ihlienworth" "1")
      (wd:Q507691 "Gemeinde Neuenkirchen" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-neuenkirchen" "0")
      (wd:Q509293 "Gemeinde Neuhaus" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-neuhaus" "0")
      (wd:Q624524 "Gemeinde Nordleda" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-nordleda" "0")
      (wd:Q505558 "Gemeinde Oberndorf" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-oberndorf" "0")
      (wd:Q505545 "Gemeinde Odisheim" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-odisheim" "0")
      (wd:Q501893 "Gemeinde Osterbruch" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-osterbruch" "0")
      (wd:Q514493 "Otterndorf" "deutschland/niedersachsen/landkreis-cuxhaven/otterndorf" "0")
      (wd:Q671777 "Gemeinde Steinau" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-steinau" "0")
      (wd:Q505591 "Gemeinde Wanna" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-wanna" "0")
      (wd:Q502938 "Gemeinde Wingst" "deutschland/niedersachsen/landkreis-cuxhaven/gemeinde-wingst" "0")
    (wd:Q3907 "Delmenhorst" "deutschland/niedersachsen/delmenhorst" "40")
    # (wd:Q5956 "Landkreis Diepholz" "deutschland/niedersachsen/landkreis-diepholz" "44")
      (wd:Q501865 "Bassum" "deutschland/niedersachsen/landkreis-diepholz/bassum" "4")
      (wd:Q498534 "Diepholz" "deutschland/niedersachsen/landkreis-diepholz/diepholz" "0")
      (wd:Q16027 "Gemeinde Stuhr" "deutschland/niedersachsen/landkreis-diepholz/gemeinde-stuhr" "2")
      (wd:Q268485 "Sulingen" "deutschland/niedersachsen/landkreis-diepholz/sulingen" "6")
      (wd:Q503751 "Syke" "deutschland/niedersachsen/landkreis-diepholz/syke" "0")
      (wd:Q503418 "Twistringen" "deutschland/niedersachsen/landkreis-diepholz/twistringen" "0")
      (wd:Q504059 "Gemeinde Wagenfeld" "deutschland/niedersachsen/landkreis-diepholz/gemeinde-wagenfeld" "0")
      (wd:Q16125 "Gemeinde Weyhe" "deutschland/niedersachsen/landkreis-diepholz/gemeinde-weyhe" "")
      (wd:Q529659 "Samtgemeinde Altes Amt Lemförde" "deutschland/niedersachsen/landkreis-diepholz/samtgemeinde-altes-amt-lemfoerde" "0")
      (wd:Q530285 "Samtgemeinde Barnstorf" "deutschland/niedersachsen/landkreis-diepholz/samtgemeinde-barnstorf" "7")
      (wd:Q481611 "Samtgemeinde Bruchhausen-Vilsen" "deutschland/niedersachsen/landkreis-diepholz/samtgemeinde-bruchhausen-vilsen" "23")
      (wd:Q451506 "Samtgemeinde Kirchdorf" "deutschland/niedersachsen/landkreis-diepholz/samtgemeinde-kirchdorf" "0")
      (wd:Q453788 "Samtgemeinde Rehden" "deutschland/niedersachsen/landkreis-diepholz/samtgemeinde-rehden" "0")
      (wd:Q487179 "Samtgemeinde Schwaförden" "deutschland/niedersachsen/landkreis-diepholz/samtgemeinde-schwafoerden" "0")
      (wd:Q487039 "Samtgemeinde Siedenburg" "deutschland/niedersachsen/landkreis-diepholz/samtgemeinde-siedenburg" "0")
    (wd:Q4174 "Emden" "deutschland/niedersachsen/emden" "0")
    (wd:Q5936 "Landkreis Emsland" "deutschland/niedersachsen/landkreis-emsland" "199")
    # (wd:Q5932 "Landkreis Friesland" "deutschland/niedersachsen/landkreis-friesland" "4")
      (wd:Q565950 "Gemeinde Bockhorn" "deutschland/niedersachsen/landkreis-friesland/gemeinde-bockhorn" "0")
      (wd:Q31084 "Jever" "deutschland/niedersachsen/landkreis-friesland/jever" "0")
      (wd:Q640905 "Gemeinde Sande" "deutschland/niedersachsen/landkreis-friesland/gemeinde-sande" "0")
      (wd:Q382061 "Schortens" "deutschland/niedersachsen/landkreis-friesland/schortens" "0")
      (wd:Q496056 "Varel" "deutschland/niedersachsen/landkreis-friesland/varel" "0")
      (wd:Q565943 "Gemeinde Wangerland" "deutschland/niedersachsen/landkreis-friesland/gemeinde-wangerland" "0")
      (wd:Q25135 "Gemeinde Wangerooge" "deutschland/niedersachsen/landkreis-friesland/gemeinde-wangerooge" "4")
      (wd:Q196850 "Gemeinde Zetel" "deutschland/niedersachsen/landkreis-friesland/gemeinde-zetel" "0")			
    # (wd:Q6053 "Landkreis Gifhorn" "deutschland/niedersachsen/landkreis-gifhorn" "9")
      (wd:Q14813 "Gifhorn" "deutschland/niedersachsen/landkreis-gifhorn/gifhorn" "9")
      (wd:Q475659 "Gemeinde Sassenburg" "deutschland/niedersachsen/landkreis-gifhorn/gemeinde-sassenburg" "0")
      (wd:Q552390 "Wittingen" "deutschland/niedersachsen/landkreis-gifhorn/wittingen" "0")
      (wd:Q519607 "Samtgemeinde Boldecker Land" "deutschland/niedersachsen/landkreis-gifhorn/samtgemeinde-" "0")
      (wd:Q187762 "Samtgemeinde Brome" "deutschland/niedersachsen/landkreis-gifhorn/samtgemeinde-brome" "0")
      (wd:Q370304 "Samtgemeinde Hankensbüttel" "deutschland/niedersachsen/landkreis-gifhorn/samtgemeinde-hankensbuettel" "0")
      (wd:Q450057 "Samtgemeinde Isenbüttel" "deutschland/niedersachsen/landkreis-gifhorn/samtgemeinde-isenbuettel" "0")
      (wd:Q460343 "Samtgemeinde Meinersen" "deutschland/niedersachsen/landkreis-gifhorn/samtgemeinde-meinersen" "0")
      (wd:Q494363 "Samtgemeinde Papenteich" "deutschland/niedersachsen/landkreis-gifhorn/samtgemeinde-papenteich" "0")
      (wd:Q531335 "Samtgemeinde Wesendorf" "deutschland/niedersachsen/landkreis-gifhorn/samtgemeinde-wesendorf" "0")
    # (wd:Q6040 "Landkreis Goslar" "deutschland/niedersachsen/landkreis-goslar" "63")
      (wd:Q522459 "Bad Harzburg" "deutschland/niedersachsen/landkreis-goslar/bad-harzburg" "0")
      (wd:Q522992 "Braunlage" "deutschland/niedersachsen/landkreis-goslar/braunlage" "0")
      (wd:Q504590 "Clausthal-Zellerfeld" "deutschland/niedersachsen/landkreis-goslar/clausthal-zellerfeld" "0")
      (wd:Q3896 "Goslar" "deutschland/niedersachsen/landkreis-goslar/goslar" "20")
      (wd:Q628260 "Langelsheim" "deutschland/niedersachsen/landkreis-goslar/langelsheim" "0")
      (wd:Q651194 "Gemeinde Liebenburg" "deutschland/niedersachsen/landkreis-goslar/gemeinde-liebenburg" "9")
      (wd:Q540934 "Seesen" "deutschland/niedersachsen/landkreis-goslar/seesen" "34")
      (wd:Q321389 "Verwaltungsbezirk Harz" "deutschland/niedersachsen/landkreis-goslar/verwaltungsbezirk-harz" "0")
    # (wd:Q6022 "Landkreis Göttingen" "deutschland/niedersachsen/landkreis-goettingen" "190")
      (wd:Q354547 "Flecken Adelebsen" "deutschland/niedersachsen/landkreis-goettingen/flecken-adelebsen" "0")
      (wd:Q537885 "Gemeinde Bad Grund" "deutschland/niedersachsen/landkreis-goettingen/gemeinde-bad-grund" "0")
      (wd:Q309505 "Gemeinde Bad Lauterberg im Harz" "deutschland/niedersachsen/landkreis-goettingen/gemeinde-bad-lauterberg-im-harz" "6")
      (wd:Q541860 "Gemeinde Bad Sachsa" "deutschland/niedersachsen/landkreis-goettingen/gemeinde-bad-sachsa" "4")
      (wd:Q621193 "Gemeinde Bovenden" "deutschland/niedersachsen/landkreis-goettingen/gemeinde-bovenden" "4")
      (wd:Q498596 "Duderstadt" "deutschland/niedersachsen/landkreis-goettingen/duderstadt" "26")
      (wd:Q671874 "Gemeinde Friedland" "deutschland/niedersachsen/landkreis-goettingen/gemeinde-friedland" "0")
      (wd:Q643951 "Gemeinde Gleichen" "deutschland/niedersachsen/landkreis-goettingen/gemeinde-gleichen" "0")
      (wd:Q3033 "Göttingen" "deutschland/niedersachsen/landkreis-goettingen/goettingen" "98")
      (wd:Q165380 "Hann. Münden" "deutschland/niedersachsen/landkreis-goettingen/hann-muenden" "0")
      (wd:Q503181 "Herzberg am Harz" "deutschland/niedersachsen/landkreis-goettingen/herzberg-am-harz" "0")
      (wd:Q327727 "Osterode am Harz" "deutschland/niedersachsen/landkreis-goettingen/osterode-am-harz" "14")
      (wd:Q630129 "Gemeinde Rosdorf" "deutschland/niedersachsen/landkreis-goettingen/gemeinde-rosdorf" "0")
      (wd:Q658603 "Gemeinde Staufenberg" "deutschland/niedersachsen/landkreis-goettingen/gemeinde-staufenberg" "0")
      (wd:Q656314 "Gemeinde Walkenried" "deutschland/niedersachsen/landkreis-goettingen/gemeinde-walkenried" "0")
      (wd:Q566648 "Samtgemeinde Dransfeld" "deutschland/niedersachsen/landkreis-goettingen/samtgemeinde-dransfeld" "38")
      (wd:Q566642 "Samtgemeinde Gieboldehausen" "deutschland/niedersachsen/landkreis-goettingen/samtgemeinde-gieboldehausen" "0")
      (wd:Q316613 "Samtgemeinde Hattorf am Harz" "deutschland/niedersachsen/landkreis-goettingen/samtgemeinde-hattorf-am-harz" "0")
      (wd:Q559863 "Samtgemeinde Radolfshausen" "deutschland/niedersachsen/landkreis-goettingen/samtgemeinde-radolfshausen" "0")
    # (wd:Q5939 "Landkreis Grafschaft Bentheim" "deutschland/niedersachsen/landkreis-grafschaft-bentheim" "159")
      (wd:Q574332 "Bad Bentheim" "deutschland/niedersachsen/landkreis-grafschaft-bentheim/bad-bentheim" "53")
      (wd:Q453926 "Samtgemeinde Emlichheim" "deutschland/niedersachsen/landkreis-grafschaft-bentheim/samtgemeinde-emlichheim" "5")
      (wd:Q504728 "Samtgemeinde Schüttorf" "deutschland/niedersachsen/landkreis-grafschaft-bentheim/samtgemeinde-schuettorf" "27")
      (wd:Q460510 "Samtgemeinde Neuenhaus" "deutschland/niedersachsen/landkreis-grafschaft-bentheim/samtgemeinde-neuenhaus" "0")
      (wd:Q453840 "Samtgemeinde Uelsen" "deutschland/niedersachsen/landkreis-grafschaft-bentheim/samtgemeinde-uelsen" "5")
      (wd:Q4133 "Nordhorn" "deutschland/niedersachsen/landkreis-grafschaft-bentheim/nordhorn" "45")
      (wd:Q556086 "Wietmarschen" "deutschland/niedersachsen/landkreis-grafschaft-bentheim/wietmarschen" "0")
    # (wd:Q5970 "Landkreis Hameln-Pyrmont" "deutschland/niedersachsen/landkreis-hameln-pyrmont" "137")
      (wd:Q381811 "Gemeinde Aerzen " "deutschland/niedersachsen/landkreis-hameln-pyrmont/gemeinde-aerzen" "0")
      (wd:Q39779 "Bad Münder am Deister " "deutschland/niedersachsen/landkreis-hameln-pyrmont/bad-muender-am-deister" "8")
      (wd:Q556352 "Bad Pyrmont " "deutschland/niedersachsen/landkreis-hameln-pyrmont/bad-pyrmont" "16")
      (wd:Q555626 "Gemeinde Coppenbrügge " "deutschland/niedersachsen/landkreis-hameln-pyrmont/gemeinde-coppenbruegge" "0")
      (wd:Q534670 "Gemeinde Emmerthal" "deutschland/niedersachsen/landkreis-hameln-pyrmont/gemeinde-emmerthal" "0")
      (wd:Q4062 "Hameln" "deutschland/niedersachsen/landkreis-hameln-pyrmont/hameln" "78")
      (wd:Q533826 "Hessisch Oldendorf" "deutschland/niedersachsen/landkreis-hameln-pyrmont/hessisch-oldendorf" "17")
      (wd:Q555604 "Gemeinde Salzhemmendorf" "deutschland/niedersachsen/landkreis-hameln-pyrmont/gemeinde-salzhemmendorf" "18")
    # (wd:Q5963 "Region Hannover" "deutschland/niedersachsen/region-hannover" "748")
				(wd:Q16022 "Barsinghausen" "deutschland/niedersachsen/region-hannover/barsinghausen" "52")
				(wd:Q555618 "Burgdorf" "deutschland/niedersachsen/region-hannover/burgdorf" "20")
				(wd:Q499873 "Burgwedel" "deutschland/niedersachsen/region-hannover/burgwedel" "30")
				(wd:Q4001 "Garbsen" "deutschland/niedersachsen/region-hannover/garbsen" "1")
				(wd:Q549864 "Gehrden" "deutschland/niedersachsen/region-hannover/gehrden" "2")
				# (wd:Q1715 "Hannover" "deutschland/niedersachsen/region-hannover/hannover" "495")
          (wd:Q400430 "Ahlem-Badenstedt-Davenstedt" "deutschland/niedersachsen/region-hannover/hannover/ahlem-badenstedt-davenstedt" "2")
          (wd:Q894709 "Bothfeld-Vahrenheide" "deutschland/niedersachsen/region-hannover/hannover/bothfeld-vahrenheide" "8")
          (wd:Q998471 "Buchholz-Kleefeld" "deutschland/niedersachsen/region-hannover/hannover/buchholz-kleefeld" "11")
          (wd:Q1271022 "Döhren-Wülfel" "deutschland/niedersachsen/region-hannover/hannover/doehren-wuelfel" "11")
          (wd:Q470577 "Herrenhausen-Stöcken" "deutschland/niedersachsen/region-hannover/hannover/herrenhausen-stoecken" "4")
          (wd:Q1743368 "Kirchrode-Bemerode-Wülferode" "deutschland/niedersachsen/region-hannover/hannover/kirchrode-bemerode-wuelferode" "3")
          (wd:Q1826001 "Linden-Limmer" "deutschland/niedersachsen/region-hannover/hannover/linden-limmer" "31")
          (wd:Q1938597 "Misburg-Anderten" "deutschland/niedersachsen/region-hannover/hannover/misburg-anderten" "8")
          (wd:Q883803 "Mitte" "deutschland/niedersachsen/region-hannover/hannover/mitte" "202")
          (wd:Q1997469 "Nord" "deutschland/niedersachsen/region-hannover/hannover/nord" "12")
          (wd:Q1417763 "Ricklingen" "deutschland/niedersachsen/region-hannover/hannover/ricklingen" "2")
          (wd:Q2381488 "Südstadt-Bult" "deutschland/niedersachsen/region-hannover/hannover/suedstadt-bult" "94")
          (wd:Q915149 "Vahrenwald-List" "deutschland/niedersachsen/region-hannover/hannover/vahrenwald-list" "107")
				(wd:Q534259 "Hemmingen" "deutschland/niedersachsen/region-hannover/hemmingen" "0")
				(wd:Q514571 "Isernhagen" "deutschland/niedersachsen/region-hannover/gemeinde-isernhagen" "1")
				(wd:Q14856 "Laatzen" "deutschland/niedersachsen/region-hannover/laatzen" "16")
				(wd:Q4158 "Langenhagen" "deutschland/niedersachsen/region-hannover/langenhagen" "0")
				(wd:Q7057 "Lehrte" "deutschland/niedersachsen/region-hannover/lehrte" "21")
				(wd:Q7014 "Neustadt am Rübenberge" "deutschland/niedersachsen/region-hannover/neustadt-am-ruebenberge" "31")
				(wd:Q501636 "Pattensen" "deutschland/niedersachsen/region-hannover/pattensen" "13")
				(wd:Q555643 "Ronnenberg" "deutschland/niedersachsen/region-hannover/ronnenberg" "25")
				(wd:Q16052 "Seelze" "deutschland/niedersachsen/region-hannover/seelze" "6")
				(wd:Q625095 "Sehnde" "deutschland/niedersachsen/region-hannover/sehnde" "9")
				(wd:Q622891 "Springe" "deutschland/niedersachsen/region-hannover/springe" "5")
				(wd:Q638645 "Gemeinde Uetze" "deutschland/niedersachsen/region-hannover/gemeinde-uetze" "0")
				(wd:Q505948 "Gemeinde Wedemark" "deutschland/niedersachsen/region-hannover/gemeinde-wedemark" "0")
				(wd:Q621469 "Gemeinde Wennigsen (Deister)" "deutschland/niedersachsen/region-hannover/gemeinde-wennigsen-deister" "2")
				(wd:Q14827 "Wunstorf" "deutschland/niedersachsen/region-hannover/wunstorf" "19")
    # (wd:Q5907 "Landkreis Harburg" "deutschland/niedersachsen/landkreis-harburg" "25")
      (wd:Q14892 "Buchholz in der Nordheide" "deutschland/niedersachsen/landkreis-harburg/buchholz-in-der-nordheide" "0")
      (wd:Q508054 "Gemeinde Neu Wulmstorf" "deutschland/niedersachsen/landkreis-harburg/gemeinde-neu-wulmstorf" "0")
      (wd:Q501683 "Gemeinde Rosengarten" "deutschland/niedersachsen/landkreis-harburg/gemeinde-rosengarten" "0")
      (wd:Q7084 "Gemeinde Seevetal" "deutschland/niedersachsen/landkreis-harburg/gemeinde-seevetal" "3")
      (wd:Q701148 "Gemeinde Stelle" "deutschland/niedersachsen/landkreis-harburg/gemeinde-stelle" "0")
      (wd:Q16000 "Winsen (Luhe)" "deutschland/niedersachsen/landkreis-harburg/winsen-luhe" "10")
      (wd:Q185848 "Samtgemeinde Elbmarsch" "deutschland/niedersachsen/landkreis-harburg/samtgemeinde-elbmarsch" "0")
      (wd:Q460326 "Samtgemeinde Hanstedt" "deutschland/niedersachsen/landkreis-harburg/samtgemeinde-hanstedt" "0")
      (wd:Q450060 "Samtgemeinde Hollenstedt" "deutschland/niedersachsen/landkreis-harburg/samtgemeinde-hollenstedt" "0")
      (wd:Q453846 "Samtgemeinde Jesteburg" "deutschland/niedersachsen/landkreis-harburg/samtgemeinde-jesteburg" "0")
      (wd:Q459359 "Samtgemeinde Salzhausen" "deutschland/niedersachsen/landkreis-harburg/samtgemeinde-salzhausen" "0")
      (wd:Q460518 "Samtgemeinde Tostedt" "deutschland/niedersachsen/landkreis-harburg/samtgemeinde-tostedt" "12")
    # (wd:Q5922 "Heidekreis" "deutschland/niedersachsen/heidekreis" "6")
      (wd:Q501609 "Bad Fallingbostel" "deutschland/niedersachsen/heidekreis/bad-fallingbostel" "0")
      (wd:Q503255 "Gemeinde Bispingen" "deutschland/niedersachsen/heidekreis/gemeinde-bispingen" "0")
      (wd:Q506599 "Munster" "deutschland/niedersachsen/heidekreis/munster" "0")
      (wd:Q501903 "Neuenkirchen" "deutschland/niedersachsen/heidekreis/gemeinde-neuenkirchen" "0")
      (wd:Q503006 "Schneverdingen" "deutschland/niedersachsen/heidekreis/schneverdingen" "0")
      (wd:Q504754 "Soltau" "deutschland/niedersachsen/heidekreis/soltau" "0")
      (wd:Q520369 "Walsrode" "deutschland/niedersachsen/heidekreis/walsrode" "6")
      (wd:Q557883 "Wietzendorf" "deutschland/niedersachsen/heidekreis/gemeinde-wietzendorf" "0")
      (wd:Q489393 "Samtgemeinde Ahlden" "deutschland/niedersachsen/heidekreis/samtgemeinde-ahlden" "0")
      (wd:Q487034 "Samtgemeinde Rethem/Aller" "deutschland/niedersachsen/heidekreis/samtgemeinde-rethem-aller" "0")
      (wd:Q487055 "Samtgemeinde Schwarmstedt" "deutschland/niedersachsen/heidekreis/samtgemeinde-schwarmstedt" "0")
      (wd:Q648962 "Bezirk Osterheide" "deutschland/niedersachsen/heidekreis/bezirk-osterheide" "0")
    # (wd:Q6047 "Landkreis Helmstedt" "deutschland/niedersachsen/landkreis-helmstedt" "74")
      # gemeindefreie Gebiete fehlen noch, siehe https://de.wikipedia.org/wiki/Landkreis_Helmstedt#Gemeinden
      (wd:Q486562 "Helmstedt" "deutschland/niedersachsen/landkreis-helmstedt/helmstedt" "25")
      (wd:Q39596 "Königslutter am Elm" "deutschland/niedersachsen/landkreis-helmstedt/koenigslutter-am-elm" "2")
      (wd:Q644249 "Gemeinde Lehre" "deutschland/niedersachsen/landkreis-helmstedt/gemeinde-lehre" "0")
      (wd:Q628304 "Schöningen" "deutschland/niedersachsen/landkreis-helmstedt/schoeningen" "47")
      (wd:Q455062 "Samtgemeinde Grasleben" "deutschland/niedersachsen/landkreis-helmstedt/samtgemeinde-grasleben" "0")
      (wd:Q460495 "Samtgemeinde Heeseberg" "deutschland/niedersachsen/landkreis-helmstedt/samtgemeinde-heeseberg" "0")
      (wd:Q460321 "Samtgemeinde Nord-Elm" "deutschland/niedersachsen/landkreis-helmstedt/samtgemeinde-nord-elm" "0")
      (wd:Q460480 "Samtgemeinde Velpke" "deutschland/niedersachsen/landkreis-helmstedt/samtgemeinde-velpke" "0")
    # (wd:Q5978 "Landkreis Hildesheim" "deutschland/niedersachsen/landkreis-hildesheim" "292")
      (wd:Q486543 "Alfeld" "deutschland/niedersachsen/landkreis-hildesheim/alfeld" "0")
      (wd:Q574412 "Gemeinde Algermissen" "deutschland/niedersachsen/landkreis-hildesheim/gemeinde-algermissen" "0")
      (wd:Q633004 "Bad Salzdetfurth" "deutschland/niedersachsen/landkreis-hildesheim/bad-salzdetfurth" "0")
      (wd:Q503392 "Bockenem" "deutschland/niedersachsen/landkreis-hildesheim/bockenem" "0")
      (wd:Q282101 "Gemeinde Diekholzen" "deutschland/niedersachsen/landkreis-hildesheim/gemeinde-diekholzen" "0")
      (wd:Q518719 "Elze" "deutschland/niedersachsen/landkreis-hildesheim/elze" "0")
      (wd:Q555597 "Gemeinde Freden (Leine)" "deutschland/niedersachsen/landkreis-hildesheim/gemeinde-freden-leine" "2")
      (wd:Q635190 "Gemeinde Giesen" "deutschland/niedersachsen/landkreis-hildesheim/gemeinde-giesen" "0")
      (wd:Q531536 "Gemeinde Harsum" "deutschland/niedersachsen/landkreis-hildesheim/gemeinde-harsum" "7")
      (wd:Q3185 "Hildesheim" "deutschland/niedersachsen/landkreis-hildesheim/hildesheim" "258")
      (wd:Q566284 "Gemeinde Holle" "deutschland/niedersachsen/landkreis-hildesheim/gemeinde-holle" "0")
      (wd:Q574356 "Gemeinde Lamspringe" "deutschland/niedersachsen/landkreis-hildesheim/gemeinde-lamspringe" "4")
      (wd:Q555657 "Gemeinde Nordstemmen" "deutschland/niedersachsen/landkreis-hildesheim/gemeinde-nordstemmen" "7")
      (wd:Q558620 "Sarstedt" "deutschland/niedersachsen/landkreis-hildesheim/sarstedt" "14")
      (wd:Q694793 "Gemeinde Schellerten" "deutschland/niedersachsen/landkreis-hildesheim/gemeinde-schellerten" "0")
      (wd:Q649621 "Gemeinde Sibbesse" "deutschland/niedersachsen/landkreis-hildesheim/gemeinde-sibbesse" "0")
      (wd:Q574384 "Gemeinde Söhlde" "deutschland/niedersachsen/landkreis-hildesheim/gemeinde-soehlde" "0")
      (wd:Q19308430 "Samtgemeinde Leinebergland" "deutschland/niedersachsen/landkreis-hildesheim/samtgemeinde-leinebergland" "0")
    # (wd:Q5973 "Landkreis Holzminden" "deutschland/niedersachsen/landkreis-holzminden" "38")
      (wd:Q58557 "Flecken Delligsen" "deutschland/niedersachsen/landkreis-holzminden/flecken-delligsen" "0")
      (wd:Q55425 "Holzminden" "deutschland/niedersachsen/landkreis-holzminden/holzminden" "0")
      (wd:Q58545 "Samtgemeinde Bevern" "deutschland/niedersachsen/landkreis-holzminden/samtgemeinde-bevern" "0")
      (wd:Q58548 "Samtgemeinde Bodenwerder-Polle" "deutschland/niedersachsen/landkreis-holzminden/samtgemeinde-bodenwerder-polle" "0")
      (wd:Q58552 "Samtgemeinde Boffzen" "deutschland/niedersachsen/landkreis-holzminden/samtgemeinde-boffzen" "5")
      (wd:Q37205 "Samtgemeinde Eschershausen-Stadtoldendorf" "deutschland/niedersachsen/landkreis-holzminden/samtgemeinde-eschershausen-stadtoldendorf" "33")
    # (wd:Q5934 "Landkreis Leer" "deutschland/niedersachsen/landkreis-leer" "196")
      (wd:Q25082 "Borkum" "deutschland/niedersachsen/landkreis-leer/borkum" "0")
      (wd:Q504541 "Gemeinde Bunde" "deutschland/niedersachsen/landkreis-leer/gemeinde-bunde" "0")
      (wd:Q559501 "Gemeinde Jemgum" "deutschland/niedersachsen/landkreis-leer/gemeinde-jemgum" "0")
      (wd:Q15984 "Leer (Ostfriesland)" "deutschland/niedersachsen/landkreis-leer/leer-ostfriesland" "53")
      (wd:Q559496 "Gemeinde Moormerland" "deutschland/niedersachsen/landkreis-leer/gemeinde-moormerland" "7")
      (wd:Q559568 "Gemeinde Ostrhauderfehn" "deutschland/niedersachsen/landkreis-leer/gemeinde-ostrhauderfehn" "0")
      (wd:Q559610 "Gemeinde Rhauderfehn" "deutschland/niedersachsen/landkreis-leer/gemeinde-rhauderfehn" "10")
      (wd:Q559624 "Gemeinde Uplengen" "deutschland/niedersachsen/landkreis-leer/gemeinde-uplengen" "0")
      (wd:Q504533 "Weener" "deutschland/niedersachsen/landkreis-leer/weener" "126")
      (wd:Q559595 "Gemeinde Westoverledingen" "deutschland/niedersachsen/landkreis-leer/gemeinde-westoverledingen" "0")
      (wd:Q121676 "Samtgemeinde Hesel" "deutschland/niedersachsen/landkreis-leer/samtgemeinde-hesel" "0")
      (wd:Q563522 "Samtgemeinde Jümme" "deutschland/niedersachsen/landkreis-leer/samtgemeinde-juemme" "0")
      (wd:Q25104 "Gemeindefreies Gebiet Insel Lütje Hörn" "deutschland/niedersachsen/landkreis-leer/luetje-horn" "0")
    # (wd:Q5913 "Landkreis Lüchow-Dannenberg" "deutschland/niedersachsen/landkreis-luechow-dannenberg" "18")
      (wd:Q320195 "Samtgemeinde Elbtalaue" "deutschland/niedersachsen/landkreis-luechow-dannenberg/samtgemeinde-elbtalaue" "7")
      (wd:Q316608 "Samtgemeinde Gartow " "deutschland/niedersachsen/landkreis-luechow-dannenberg/samtgemeinde-gartow " "0")
      (wd:Q320602 "Samtgemeinde Lüchow (Wendland)" "deutschland/niedersachsen/landkreis-luechow-dannenberg/samtgemeinde-luechow-wendland" "11")
      # (wd:Q875514 "Gemeindefreies Gebiet Gartow" "deutschland/niedersachsen/landkreis-luechow-dannenberg/gemeindefreies-gebiet-gartow" "")
      # (wd:Q875908 "Gemeindefreies Gebiet Göhrde" "deutschland/niedersachsen/landkreis-luechow-dannenberg/samtgemeinde-goehrde" "0")
    # (wd:Q5910 "Landkreis Lüneburg" "deutschland/niedersachsen/landkreis-lueneburg" "77")
      (wd:Q355913 "Gemeinde Adendorf" "deutschland/niedersachsen/landkreis-lueneburg/gemeinde-adendorf" "2")
      (wd:Q479687 "Gemeinde Amt Neuhaus" "deutschland/niedersachsen/landkreis-lueneburg/gemeinde-amt-neuhaus" "0")
      (wd:Q567445 "Bleckede" "deutschland/niedersachsen/landkreis-lueneburg/bleckede" "3")
      (wd:Q3920 "Lüneburg" "deutschland/niedersachsen/landkreis-lueneburg/lueneburg" "72")
      (wd:Q460380 "Samtgemeinde Amelinghausen" "deutschland/niedersachsen/landkreis-lueneburg/samtgemeinde-amelinghausen" "0")
      (wd:Q458287 "Samtgemeinde Bardowick" "deutschland/niedersachsen/landkreis-lueneburg/samtgemeinde-bardowick" "0")
      (wd:Q316740 "Samtgemeinde Dahlenburg" "deutschland/niedersachsen/landkreis-lueneburg/samtgemeinde-dahlenburg" "0")
      (wd:Q315001 "Samtgemeinde Gellersen" "deutschland/niedersachsen/landkreis-lueneburg/samtgemeinde-gellersen" "0")
      (wd:Q452774 "Samtgemeinde Ilmenau" "deutschland/niedersachsen/landkreis-lueneburg/samtgemeinde-ilmenau" "0")
      (wd:Q460421 "Samtgemeinde Ostheide" "deutschland/niedersachsen/landkreis-lueneburg/samtgemeinde-ostheide" "0")
      (wd:Q316734 "Samtgemeinde Scharnebeck" "deutschland/niedersachsen/landkreis-lueneburg/samtgemeinde-scharnebeck" "0")
    # (wd:Q5958 "Landkreis Nienburg/Weser" "deutschland/niedersachsen/landkreis-nienburg-weser" "131")
      (wd:Q16079 "Nienburg/Weser" "deutschland/niedersachsen/landkreis-nienburg-weser/nienburg-weser" "50")
      (wd:Q541873 "Rehburg-Loccum" "deutschland/niedersachsen/landkreis-nienburg-weser/rehburg-loccum" "29")
      (wd:Q666695 "Gemeinde Steyerberg" "deutschland/niedersachsen/landkreis-nienburg-weser/gemeinde-steyerberg" "0")
      (wd:Q486777 "Samtgemeinde Grafschaft Hoya" "deutschland/niedersachsen/landkreis-nienburg-weser/samtgemeinde-grafschaft-joya" "33")
      (wd:Q451354 "Samtgemeinde Heemsen" "deutschland/niedersachsen/landkreis-nienburg-weser/samtgemeinde-heemsen" "0")
      (wd:Q443984 "Samtgemeinde Mittelweser" "deutschland/niedersachsen/landkreis-nienburg-weser/samtgemeinde-mittelweser" "8")
      (wd:Q453145 "Samtgemeinde Steimbke" "deutschland/niedersachsen/landkreis-nienburg-weser/samtgemeinde-steimbke" "0")
      (wd:Q461179 "Samtgemeinde Uchte" "deutschland/niedersachsen/landkreis-nienburg-weser/samtgemeinde-uchte" "11")
      (wd:Q106393994 "Samtgemeinde Weser-Aue" "deutschland/niedersachsen/landkreis-nienburg-weser/samtgemeinde-weser-aue" "0")
      (wd:Q6018 "Landkreis Northeim" "deutschland/niedersachsen/landkreis-northeim" "127")
      (wd:Q2936 "Oldenburg (Oldb)" "deutschland/niedersachsen/oldenburg-oldb" "8")
      (wd:Q5952 "Landkreis Oldenburg" "deutschland/niedersachsen/landkreis-oldenburg" "12")
      (wd:Q2916 "Osnabrück" "deutschland/niedersachsen/osnabrueck" "10")
      (wd:Q5940 "Landkreis Osnabrück" "deutschland/niedersachsen/landkreis-osnabrueck" "118")
      (wd:Q5926 "Landkreis Osterholz" "deutschland/niedersachsen/landkreis-osterholz" "64")
      (wd:Q6045 "Landkreis Peine" "deutschland/niedersachsen/landkreis-peine" "57")
      (wd:Q5923 "Landkreis Rotenbrug (Wümme)" "deutschland/niedersachsen/landkreis-rotenburg-wuemme" "43")
    # (wd:Q3200 "Salzgitter" "deutschland/niedersachsen/salzgitter" "12")
      (wd:Q17590743 "Ortschaft Nord" "deutschland/niedersachsen/salzgitter/ortschaft-nord" "12")
      (wd:Q17590745 "Ortschaft Nordost" "deutschland/niedersachsen/salzgitter/ortschaft-nordost" "0")
      (wd:Q17590747 "Ortschaft Nordwest" "deutschland/niedersachsen/salzgitter/ortschaft-nordwest" "0")
      (wd:Q17590748 "Ortschaft Ost" "deutschland/niedersachsen/salzgitter/ortschaft-ost" "0")
      (wd:Q17590750 "Ortschaft Süd" "deutschland/niedersachsen/salzgitter/ortschaft-sued" "0")
      (wd:Q17590751 "Ortschaft Südost" "deutschland/niedersachsen/salzgitter/ortschaft-suedost" "0")
      (wd:Q17590752 "Ortschaft West" "deutschland/niedersachsen/salzgitter/ortschaft-west" "0")
    (wd:Q5966 "Landkreis Schaumburg" "deutschland/niedersachsen/landkreis-schaumburg" "0")
    (wd:Q5906 "Landkreis Stade" "deutschland/niedersachsen/landkreis-stade" "25")
    (wd:Q5915 "Landkreis Uelzen" "deutschland/niedersachsen/landkreis-uelzen" "17")
    (wd:Q5941 "Landkreis Vechta" "deutschland/niedersachsen/landkreis-vechta" "21")
    (wd:Q5927 "Landkreis Verden" "deutschland/niedersachsen/landkreis-verden" "232")
    (wd:Q5948 "Landkreis Wesermarsch" "deutschland/niedersachsen/landkreis-wesermarsch" "24")
    (wd:Q3857 "Wilhelmshaven" "deutschland/niedersachsen/wilhelmshaven" "20")
    (wd:Q5931 "Landkreis Wittmund" "deutschland/niedersachsen/landkreis-wittmund" "29")
    (wd:Q6041 "Landkreis Wolfenbüttel" "deutschland/niedersachsen/landkreis-wolfenbuettel" "11")
    (wd:Q3014 "Wolfsburg" "deutschland/niedersachsen/wolfsburg" "0")	
    }
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label {
	bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" .
  }
}
