#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Deutschland mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape  ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number) {
    (wd:Q1197 "Niedersachsen" "deutschland/niedersachsen" "" "4128")
    (wd:Q5947 "Landkreis Ammerland" "deutschland/niedersachsen/landkreis-ammerland" "" "1")
    (wd:Q5929 "Landkreis Aurich" "deutschland/niedersachsen/landkreis-aurich" "" "8")
    (wd:Q2773 "Braunschweig" "deutschland/niedersachsen/braunschweig" "414")
    (wd:Q5919 "Landkreis Celle" "deutschland/niedersachsen/landkreis-celle" "115")
    (wd:Q5945 "Landkreis Cloppenburg" "deutschland/niedersachsen/landkreis-cloppenburg" "41")
    (wd:Q5897 "Landkreis Cuxhaven" "deutschland/niedersachsen/landkreis-cuxhaven" "green" "51")
    (wd:Q3907 "Delmenhorst" "deutschland/niedersachsen/delmenhorst" "" "40")
    (wd:Q5956 "Landkreis Diepholz" "deutschland/niedersachsen/landkreis-diepholz" "" "44")
    (wd:Q4174 "Emden" "deutschland/niedersachsen/emden" "" "0")
    (wd:Q5936 "Landkreis Emsland" "deutschland/niedersachsen/landkreis-emsland" "" "199")
    (wd:Q5932 "Landkreis Friesland" "deutschland/niedersachsen/landkreis-friesland" "" "4")
    (wd:Q6040 "Landkreis Goslar" "deutschland/niedersachsen/landkreis-goslar" "63")
    (wd:Q6022 "Landkreis Göttingen" "deutschland/niedersachsen/landkreis-goettingen" "190")
    (wd:Q5939 "Landkreis Grafschaft Bentheim" "deutschland/niedersachsen/landkreis-grafschaft-bentheim" "159")
    (wd:Q5970 "Landkreis Hameln-Pyrmont" "deutschland/niedersachsen/landkreis-hameln-pyrmont" "137")
    (wd:Q5963 "Region Hannover " "deutschland/niedersachsen/region-hannover" "748")
    (wd:Q5907 "Landkreis Harburg" "deutschland/niedersachsen/landkreis-harburg" "27")
    (wd:Q5922 "Heidekreis" "deutschland/niedersachsen/heidekreis" "6")
    (wd:Q6047 "Landkreis Helmstedt" "deutschland/niedersachsen/landkreis-helmstedt" "74")
    (wd:Q5978 "Landkreis Hildesheim" "deutschland/niedersachsen/landkreis-hildesheim" "292")
    (wd:Q5973 "Landkreis Holzminden" "deutschland/niedersachsen/landkreis-holzminden" "38")
    (wd:Q5934 "Landkreis Leer" "deutschland/niedersachsen/landkreis-leer" "196")
    (wd:Q5913 "Landkreis Lüchow-Dannenberg" "deutschland/niedersachsen/landkreis-luechow-dannenberg" "18")
    (wd:Q5910 "Landkreis Lüneburg" "deutschland/niedersachsen/landkreis-lueneburg" "77")
    (wd:Q5958 "Landkreis Nienburg/Weser" "deutschland/niedersachsen/landkreis-nienburg-weser" "131")
    (wd:Q6018 "Landkreis Northeim" "deutschland/niedersachsen/landkreis-northeim" "127")
    (wd:Q2936 "Oldenburg (Oldb)" "deutschland/niedersachsen/oldenburg-oldb" "8")
    (wd:Q5952 "Landkreis Oldenburg" "deutschland/niedersachsen/landkreis-oldenburg" "12")
    (wd:Q2916 "Osnabrück" "deutschland/niedersachsen/osnabrueck" "10")
    (wd:Q5940 "Landkreis Osnabrück" "deutschland/niedersachsen/landkreis-osnabrueck" "118")
    (wd:Q5926 "Landkreis Osterholz" "deutschland/niedersachsen/landkreis-osterholz" "64")
    (wd:Q6045 "Landkreis Peine" "deutschland/niedersachsen/landkreis-peine" "57")
    (wd:Q5923 "Landkreis Rotenbrug (Wümme)" "deutschland/niedersachsen/landkreis-rotenburg-wuemme" "43")
    (wd:Q3200 "Salzgitter" "deutschland/niedersachsen/salzgitter" "12")
    (wd:Q5966 "Landkreis Schaumburg" "deutschland/niedersachsen/landkreis-schaumburg" "0")
    (wd:Q5906 "Landkreis Stade" "deutschland/niedersachsen/landkreis-stade" "25")
    (wd:Q5915 "Landkreis Uelzen" "deutschland/niedersachsen/landkreis-uelzen" "17")
    (wd:Q5941 "Landkreis Vechta" "deutschland/niedersachsen/landkreis-vechta" "21")
    (wd:Q5927 "Landkreis Verden" "deutschland/niedersachsen/landkreis-verden" "232")
    (wd:Q5948 "Landkreis Wesermarsch" "deutschland/niedersachsen/landkreis-wesermarsch" "24")
    (wd:Q3857 "Wilhelmshaven" "deutschland/niedersachsen/wilhelmshaven" "20")
    (wd:Q5931 "Landkreis Wittmund" "deutschland/niedersachsen/landkreis-wittmund" "29")
    (wd:Q6041 "Landkreis Wolfenbüttel" "deutschland/niedersachsen/landkreis-wolfenbuettel" "11")
    (wd:Q3014 "Wolfsburg" "deutschland/niedersachsen/wolfsburg" "0")	
      		}
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label {
	bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" .
  }
}