#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten im Saarland mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape  ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number) {
    (wd:Q1201 "Saarland" "deutschland/saarland" "")
        (wd:Q6802 "Landkreis Merzig-Wadern" "deutschland/saarland/landkreis-merzig-wadern" "")
        (wd:Q6799 "Landkreis Neunkirchen" "deutschland/saarland/landkreis-neunkirchen" "")
        (wd:Q6805 "Regionalverband Saarbrücken" "deutschland/saarland/regionalverband-saarbruecken" "")
            (wd:Q1724 "Saarbrücken" "deutschland/saarland/regionalverband-saarbruecken/saarbruecken" "") # P3896 fehlt
                (wd:Q20850653 "Mitte" "deutschland/saarland/regionalverband-saarbruecken/saarbruecken/mitte" "") # P3896 fehlt
                (wd:Q20850634 "West" "deutschland/saarland/regionalverband-saarbruecken/saarbruecken/west" "") # P3896 fehlt
                (wd:Q20850647 "Dudweiler" "deutschland/saarland/regionalverband-saarbruecken/saarbruecken/dudweiler" "") # P3896 fehlt
                (wd:Q20850649 "Halberg" "deutschland/saarland/regionalverband-saarbruecken/saarbruecken/halberg" "") # P3896 fehlt
        (wd:Q6794 "Landkreis Saarlouis" "deutschland/saarland/landkreis-saarlouis" "")
        (wd:Q6793 "Saarpfalz-Kreis" "deutschland/saarland/saarpfalz-kreis" "")
        (wd:Q6789 "Landkreis St. Wendel" "deutschland/saarland/landkreis-st-wendel" "")
		}
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label {
	bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" .
  }
}