#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Schleswig-Holstein mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape  ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number) {
    (wd:Q1194 "Schleswig-Holstein" "deutschland/schleswig-holstein" "")
        (wd:Q2947 "Kreis Dithmarschen" "deutschland/schleswig-holstein/kreis-dithmarschen" "")
        (wd:Q3798 "Flensburg" "deutschland/schleswig-holstein/flensburg" "Die Einteilung der Stadtbezirke ist noch unklar")
        (wd:Q3000 "Kreis Herzogtum Lauenburg" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg" "")
        (wd:Q1707 "Kiel" "deutschland/schleswig-holstein/kiel" "Die Einteilung der Stadtbezirke ist noch unklar")
        (wd:Q2843 "Lübeck" "deutschland/schleswig-holstein/luebeck" "Die Einteilung der Stadtbezirke ist noch unklar")
        (wd:Q2937 "Kreis Nordfriesland" "deutschland/schleswig-holstein/kreis-nordfriesland" "")
        (wd:Q3879 "Neumünster" "deutschland/schleswig-holstein/neumuenster" "")
        (wd:Q2975 "Kreis Ostholstein" "deutschland/schleswig-holstein/kreis-ostholstein" "")
        (wd:Q3006 "Kreis Pinneberg" "deutschland/schleswig-holstein/kreis-pinneberg" "")
        (wd:Q2970 "Kreis Plön" "deutschland/schleswig-holstein/kreis-ploen" "")
        (wd:Q2967 "Kreis Rendsburg-Eckernförde" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde" "")
        (wd:Q2941 "Kreis Schleswig-Flensburg" "deutschland/schleswig-holstein/kreis-schleswig-flensburg" "")
        (wd:Q2980 "Kreis Segeberg" "deutschland/schleswig-holstein/kreis-segeberg" "")
        (wd:Q3011 "Kreis Steinburg" "deutschland/schleswig-holstein/kreis-steinburg" "")
        (wd:Q3003 "Kreis Stormarn" "deutschland/schleswig-holstein/kreis-stormarn" "")
		}
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label {
	bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" .
  }
}