#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Schleswig-Holstein mit der Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number) {
    # (wd:Q2947 "Kreis Dithmarschen" "deutschland/schleswig-holstein/kreis-dithmarschen" "14")
      (wd:Q516635 "Brunsbüttel" "deutschland/schleswig-holstein/kreis-dithmarschen/brunsbuettel" "0")
      (wd:Q492322 "Heide" "deutschland/schleswig-holstein/kreis-dithmarschen/heide" "7")
      (wd:Q479068 "Amt Burg-Sankt Michaelisdonn" "deutschland/schleswig-holstein/kreis-dithmarschen/amt-burg-sankt-michaelisdonn" "2")
      (wd:Q479091 "Amt Büsum-Wesselburen" "deutschland/schleswig-holstein/kreis-dithmarschen/amt-buesum-wesselburen" "0")
      (wd:Q479481 "Amt Kirchspielslandgemeinde Heider Umland" "deutschland/schleswig-holstein/kreis-dithmarschen/amt-kirchspielslandgemeinde-heider-umland" "0")
      (wd:Q479499 "Amt Kirchspielslandgemeinden Eider" "deutschland/schleswig-holstein/kreis-dithmarschen/amt-kirchspielslandgemeinden-eider" "0")
      (wd:Q479617 "Amt Marne-Nordsee" "deutschland/schleswig-holstein/kreis-dithmarschen/amt-marne-nordsee" "0")
      (wd:Q479644 "Amt Mitteldithmarschen" "deutschland/schleswig-holstein/kreis-dithmarschen/amt-mitteldithmarschen" "5")
    (wd:Q3798 "Flensburg" "deutschland/schleswig-holstein/flensburg" "52")
    # (wd:Q3000 "Kreis Herzogtum Lauenburg" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg" "6")
      (wd:Q494790 "Geesthacht" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/geesthacht" "2")
      (wd:Q492380 "Lauenburg/Elbe" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/lauenburg-elbe" "0")
      (wd:Q498036 "Mölln" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/moelln" "0")
      (wd:Q490025 "Ratzeburg" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/ratzeburg" "1")
      (wd:Q569643 "Schwarzenbek" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/schwarzenbek" "0")
      (wd:Q552545 "Gemeinde Wentorf bei Hamburg" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/gemeinde-wentorf-bei-hamburg" "0")
      (wd:Q478974 "Amt Berkenthin" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/amt-berkenthin" "0")
      (wd:Q479043 "Amt Breitenfelde" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/amt-breitenfelde" "0")
      (wd:Q479088 "Amt Büchen" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/amt-buechen" "0")
      (wd:Q479387 "Amt Hohe Elbgeest" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/amt-hohe-elbgeest" "3")
      (wd:Q479552 "Amt Lauenburgische Seen" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/amt-lauenburgische-seen" "0")
      (wd:Q461903 "Amt Lütau" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/amt-luetau" "0")
      (wd:Q151347 "Amt Sandesneben-Nusse" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/amt-sandesneben-nusse" "0")
      (wd:Q479949 "Amt Schwarzenbek-Land" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg/amt-schwarzenbek-land" "0")
    (wd:Q1707 "Kiel" "deutschland/schleswig-holstein/kiel" "265")
    (wd:Q2843 "Lübeck" "deutschland/schleswig-holstein/luebeck" "233")
    # (wd:Q2937 "Kreis Nordfriesland" "deutschland/schleswig-holstein/kreis-nordfriesland" "59")
      (wd:Q21065 "Friedrichstadt" "deutschland/schleswig-holstein/kreis-nordfriesland/friedrichstadt" "32")
      (wd:Q21159 "Husum" "deutschland/schleswig-holstein/kreis-nordfriesland/husum" "1")
      (wd:Q21043 "Gemeinde Reußenköge" "deutschland/schleswig-holstein/kreis-nordfriesland/gemeinde-reussenkoege" "0")
      (wd:Q21008 "Gemeinde Sylt" "deutschland/schleswig-holstein/kreis-nordfriesland/gemeinde-sylt" "2")
      (wd:Q21018 "Tönning" "deutschland/schleswig-holstein/kreis-nordfriesland/toenning" "0")
      (wd:Q20861 "Amt Eiderstedt" "deutschland/schleswig-holstein/kreis-nordfriesland/amt-eiderstedt" "0")
      (wd:Q20706 "Amt Föhr-Amrum" "deutschland/schleswig-holstein/kreis-nordfriesland/amt-foehr-amrum" "2")
      (wd:Q20701 "Amt Landschaft Sylt" "deutschland/schleswig-holstein/kreis-nordfriesland/amt-landschaft-sylt" "2")
      (wd:Q20698 "Amt Mittleres Nordfriesland" "deutschland/schleswig-holstein/kreis-nordfriesland/amt-mittleres-nordfriesland" "0")
      (wd:Q20704 "Amt Nordsee-Treene" "deutschland/schleswig-holstein/kreis-nordfriesland/amt-nordsee-treene" "0")
      (wd:Q21015 "Amt Pellworm" "deutschland/schleswig-holstein/kreis-nordfriesland/amt-pellworm" "0")
      (wd:Q20737 "Amt Südtondern" "deutschland/schleswig-holstein/kreis-nordfriesland/amt-suedtondern" "0")
      (wd:Q20697 "Amt Viöl" "deutschland/schleswig-holstein/kreis-nordfriesland/amt-vioel" "0")
    (wd:Q3879 "Neumünster" "deutschland/schleswig-holstein/neumuenster" "33")
    # (wd:Q2975 "Kreis Ostholstein" "deutschland/schleswig-holstein/kreis-ostholstein" "17")
      (wd:Q402773 "Gemeinde Ahrensbök" "deutschland/schleswig-holstein/kreis-ostholstein/gemeinde-ahrensboek" "0")
      (wd:Q516432 "Bad Schwartau" "deutschland/schleswig-holstein/kreis-ostholstein/bad-schwartau" "0")
      # (wd:Q554043 "Gemeinde Bosau" "deutschland/schleswig-holstein/kreis-ostholstein/gemeinde-bosau" "0") wird verwaltet durch Ostholstein, liegt im Amt Großer Plöner See
      (wd:Q637728 "Gemeinde Dahme" "deutschland/schleswig-holstein/kreis-ostholstein/gemeinde-dahme" "0")
      (wd:Q490445 "Eutin" "deutschland/schleswig-holstein/kreis-ostholstein/eutin" "3")
      (wd:Q3172 "Fehmarn" "deutschland/schleswig-holstein/kreis-ostholstein/fehmarn" "0")
      (wd:Q541739 "Gemeinde Grömitz" "deutschland/schleswig-holstein/kreis-ostholstein/gemeinde-groemitz" "0")
      (wd:Q555085 "Gemeinde Grube" "deutschland/schleswig-holstein/kreis-ostholstein/gemeinde-grube" "0")
      (wd:Q516540 "Heiligenhafen" "deutschland/schleswig-holstein/kreis-ostholstein/heiligenhafen" "0")
      (wd:Q551387 "Gemeinde Kellenhusen" "deutschland/schleswig-holstein/kreis-ostholstein/gemeinde-kellenhusen" "0")
      (wd:Q522056 "Gemeinde Malente" "deutschland/schleswig-holstein/kreis-ostholstein/gemeinde-malente" "0")
      (wd:Q499861 "Neustadt in Holstein" "deutschland/schleswig-holstein/kreis-ostholstein/neustadt-in-holstein" "1")
      (wd:Q496435 "Oldenburg in Holstein" "deutschland/schleswig-holstein/kreis-ostholstein/oldenburg-in-holstein" "7")
      (wd:Q629480 "Gemeinde Ratekau" "deutschland/schleswig-holstein/kreis-ostholstein/gemeinde-ratekau" "0")
      (wd:Q541628 "Gemeinde Scharbeutz" "deutschland/schleswig-holstein/kreis-ostholstein/gemeinde-scharbeutz" "0")
      (wd:Q551818 "Gemeinde Stockelsdorf" "deutschland/schleswig-holstein/kreis-ostholstein/gemeinde-stockelsdorf" "2")
      (wd:Q554068 "Gemeinde Süsel" "deutschland/schleswig-holstein/kreis-ostholstein/gemeinde-suesel" "0")
      (wd:Q541750 "Gemeinde Timmendorfer Strand" "deutschland/schleswig-holstein/kreis-ostholstein/gemeinde-timmendorfer-strand" "0")
      (wd:Q479559 "Amt Lensahn" "deutschland/schleswig-holstein/kreis-ostholstein/amt-lensahn" "0")
      (wd:Q479750 "Amt Oldenburg-Land" "deutschland/schleswig-holstein/kreis-ostholstein/amt-oldenburg-land" "0")
      (wd:Q479763 "Amt Ostholstein-Mitte" "deutschland/schleswig-holstein/kreis-ostholstein/amt-ostholstein-mitte" "0")
    # (wd:Q3006 "Kreis Pinneberg" "deutschland/schleswig-holstein/kreis-pinneberg" "67")
      (wd:Q516930 "Barmstedt" "deutschland/schleswig-holstein/kreis-pinneberg/barmstedt" "7")
      (wd:Q574242 "Gemeinde Bönningstedt" "deutschland/schleswig-holstein/kreis-pinneberg/gemeinde-boenningstedt" "0")
      (wd:Q6845 "Elmshorn" "deutschland/schleswig-holstein/kreis-pinneberg/elmshorn" "25")
      (wd:Q542824 "Gemeinde Halstenbek" "deutschland/schleswig-holstein/kreis-pinneberg/gemeinde-halstenbek" "0")
      (wd:Q566123 "Gemeinde Hasloh" "deutschland/schleswig-holstein/kreis-pinneberg/gemeinde-hasloh" "0")
      (wd:Q3038 "Gemeinde Helgoland" "deutschland/schleswig-holstein/kreis-pinneberg/gemeinde-helgoland" "6")
      (wd:Q7074 "Pinneberg" "deutschland/schleswig-holstein/kreis-pinneberg/pinneberg" "3")
      (wd:Q516623 "Quickborn" "deutschland/schleswig-holstein/kreis-pinneberg/quickborn" "8")
      (wd:Q542849 "Gemeinde Rellingen" "deutschland/schleswig-holstein/kreis-pinneberg/gemeinde-rellingen" "0")
      (wd:Q503893 "Schenefeld" "deutschland/schleswig-holstein/kreis-pinneberg/schenefeld" "0")
      (wd:Q504812 "Tornesch" "deutschland/schleswig-holstein/kreis-pinneberg/tornesch" "1")
      (wd:Q1404 "Uetersen" "deutschland/schleswig-holstein/kreis-pinneberg/uetersen" "11")
      (wd:Q4356 "Wedel" "deutschland/schleswig-holstein/kreis-pinneberg/wedel" "5")
      (wd:Q479195 "Amt Elmshorn-Land" "deutschland/schleswig-holstein/kreis-pinneberg/amt-elmshorn-land" "0")
      (wd:Q202318 "Amt Hörnerkirchen" "deutschland/schleswig-holstein/kreis-pinneberg/amt-hoernerkirchen" "0")
      (wd:Q47104801 "Amt Geest und Marsch Südholstein" "deutschland/schleswig-holstein/kreis-pinneberg/amt-geest-und-marsch-suedholstein" "0")
      (wd:Q479798 "Amt Pinnau" "deutschland/schleswig-holstein/kreis-pinneberg/amt-pinnau" "0")
      (wd:Q6321437 "Amt Rantzau" "deutschland/schleswig-holstein/kreis-pinneberg/amt-rantzau" "0")
    # (wd:Q2970 "Kreis Plön" "deutschland/schleswig-holstein/kreis-ploen" "3")
      (wd:Q682175 "Gemeinde Ascheberg" "deutschland/schleswig-holstein/kreis-ploen/gemeinde-ascheberg" "0")
      (wd:Q636514 "Gemeinde Bönebüttel" "deutschland/schleswig-holstein/kreis-ploen/gemeinde-boenebuettel" "0")
      (wd:Q669091 "Gemeinde Bösdorf" "deutschland/schleswig-holstein/kreis-ploen/gemeinde-boesdorf" "0")
      (wd:Q497060 "Plön" "deutschland/schleswig-holstein/kreis-ploen/ploen" "0")
      (wd:Q500171 "Preetz" "deutschland/schleswig-holstein/kreis-ploen/preetz" "0")
      (wd:Q640402 "Schwentinental" "deutschland/schleswig-holstein/kreis-ploen/schwentinental" "0")
      (wd:Q473796 "Amt Bokhorst-Wankendorf" "deutschland/schleswig-holstein/kreis-ploen/amt-bokhorst-wankendorf" "2")
      (wd:Q479326 "Amt Großer Plöner See" "deutschland/schleswig-holstein/kreis-ploen/amt-grosser-ploener-see" "0")
      (wd:Q479601 "Amt Lütjenburg" "deutschland/schleswig-holstein/kreis-ploen/amt-luetjenburg" "0")
      (wd:Q479816 "Amt Preetz-Land" "deutschland/schleswig-holstein/kreis-ploen/amt-preetz-land" "0")
      (wd:Q479820 "Amt Probstei" "deutschland/schleswig-holstein/kreis-ploen/amt-probstei" "0")
      (wd:Q479927 "Amt Schrevenborn" "deutschland/schleswig-holstein/kreis-ploen/amt-schrevenborn" "1")
      (wd:Q479976 "Amt Selent/Schlesen" "deutschland/schleswig-holstein/kreis-ploen/amt-selent-schlesen" "0")
    # (wd:Q2967 "Kreis Rendsburg-Eckernförde" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde" "49")
      (wd:Q437296 "Gemeinde Altenholz" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/gemeinde-altenholz" "0")
      (wd:Q571940 "Büdelsdorf" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/buedelsdorf" "1")
      (wd:Q490453 "Eckernförde" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/eckernfoerde" "6")
      (wd:Q565416 "Gemeinde Kronshagen" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/gemeinde-kronshagen" "0")
      (wd:Q490457 "Rendsburg" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/rendsburg" "35")
      (wd:Q556245 "Gemeinde Wasbek" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/gemeinde-wasbek" "0")
      (wd:Q478858 "Amt Achterwehr" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/amt-achterwehr" "0")
      (wd:Q479010 "Amt Bordesholm" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/amt-bordesholm" "0")
      (wd:Q479144 "Amt Dänischenhagen" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/amt-daenischenhagen" "0")
      (wd:Q479146 "Amt Dänischer Wohld" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/amt-daenischer-wohld" "0")
      (wd:Q479162 "Amt Eiderkanal" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/amt-eiderkanal" "0")
      (wd:Q113342498 "Amt Eidertal" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/amt-eidertal" "0")
      (wd:Q479236 "Amt Fockbek" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/amt-fockbek" "0")
      (wd:Q479396 "Amt Hohner Harde" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/amt-hohner-harde" "0")
      (wd:Q473904 "Amt Hüttener Berge" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/amt-huettener-berge" "0")
      (wd:Q479439 "Amt Jevenstedt" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/amt-jevenstedt" "0")
      (wd:Q283467 "Amt Mittelholstein" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/amt-mittelholstein" "2")
      (wd:Q479728 "Amt Nortorfer Land" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/amt-nortorfer-land" "0")
      (wd:Q479907 "Amt Schlei-Ostsee" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde/amt-schlei-ostsee" "0")
    # (wd:Q2941 "Kreis Schleswig-Flensburg" "deutschland/schleswig-holstein/kreis-schleswig-flensburg" "15")
      (wd:Q494617 "Glücksburg" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/gluecksburg" "0")
      (wd:Q551497 "Gemeinde Handewitt" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/gemeinde-handewitt" "0")
      (wd:Q539243 "Gemeinde Harrislee" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/gemeinde-harrislee" "0")
      (wd:Q516567 "Kappeln" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/kappeln" "0")
      (wd:Q501661 "Schleswig" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/schleswig" "0")
      (wd:Q473908 "Amt Arensharde" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/amt-arensharde" "0")
      (wd:Q479158 "Amt Eggebek" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/amt-eggebek" "0")
      (wd:Q472949 "Amt Geltinger Bucht" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/amt-geltinger-bucht" "0")
      (wd:Q457404 "Amt Haddeby" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/amt-haddeby" "0")
      (wd:Q460489 "Amt Hürup" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/amt-huerup" "0")
      (wd:Q460313 "Amt Kappeln-Land" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/amt-kappeln-land" "0")
      (wd:Q473792 "Amt Kropp-Stapelholm" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/amt-kropp-stapelholm" "0")
      (wd:Q461037 "Amt Langballig" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/amt-langballig" "0")
      (wd:Q459345 "Amt Mittelangeln" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/amt-mittelangeln" "0")
      (wd:Q479744 "Amt Oeversee" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/amt-oeversee" "0")
      (wd:Q479884 "Amt Schafflund" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/amt-schafflund" "0")
      (wd:Q480026 "Amt Südangeln" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/amt-suedangeln" "0")
      (wd:Q316729 "Amt Süderbrarup" "deutschland/schleswig-holstein/kreis-schleswig-flensburg/amt-suederbrarup" "0")
    # (wd:Q2980 "Kreis Segeberg" "deutschland/schleswig-holstein/kreis-segeberg" "13")
      (wd:Q523987 "Bad Bramstedt" "deutschland/schleswig-holstein/kreis-segeberg/bad-bramstedt" "0")
      (wd:Q496050 "Bad Segeberg" "deutschland/schleswig-holstein/kreis-segeberg/bad-segeberg" "0")
      (wd:Q554129 "Gemeinde Ellerau" "deutschland/schleswig-holstein/kreis-segeberg/gemeinde-ellerau" "0")
      (wd:Q508077 "Gemeinde Henstedt-Ulzburg" "deutschland/schleswig-holstein/kreis-segeberg/gemeinde-henstedt-ulzburg" "0")
      (wd:Q492390 "Kaltenkirchen" "deutschland/schleswig-holstein/kreis-segeberg/kaltenkirchen" "0")
      (wd:Q3928 "Norderstedt" "deutschland/schleswig-holstein/kreis-segeberg/norderstedt" "0")
      (wd:Q536506 "Wahlstedt" "deutschland/schleswig-holstein/kreis-segeberg/wahlstedt" "0")
      (wd:Q479453 "Amt Auenland Südholstein" "deutschland/schleswig-holstein/kreis-segeberg/amt-auenland-suedholstein" "0")
      (wd:Q478927 "Amt Bad Bramstedt-Land" "deutschland/schleswig-holstein/kreis-segeberg/amt-bad-bramstedt-land" "0")
      (wd:Q479006 "Amt Boostedt-Rickling" "deutschland/schleswig-holstein/kreis-segeberg/amt-boostedt-rickling" "0")
      (wd:Q479022 "Amt Bornhöved" "deutschland/schleswig-holstein/kreis-segeberg/amt-bornhoeved" "0")
      (wd:Q479430 "Amt Itzstedt" "deutschland/schleswig-holstein/kreis-segeberg/amt-itzstedt" "0")
      (wd:Q479501 "Amt Kisdorf" "deutschland/schleswig-holstein/kreis-segeberg/amt-kisdorf" "0")
      (wd:Q479557 "Amt Leezen" "deutschland/schleswig-holstein/kreis-segeberg/amt-leezen" "0")
      (wd:Q480062 "Amt Trave-Land" "deutschland/schleswig-holstein/kreis-segeberg/amt-trave-land" "0")
    # (wd:Q3011 "Kreis Steinburg" "deutschland/schleswig-holstein/kreis-steinburg" "32")
      (wd:Q377277 "Glückstadt" "deutschland/schleswig-holstein/kreis-steinburg/glueckstadt" "0")
      (wd:Q16073 "Itzehoe" "deutschland/schleswig-holstein/kreis-steinburg/itzehoe" "0")
      (wd:Q506560 "Wilster" "deutschland/schleswig-holstein/kreis-steinburg/wilster" "0")
      (wd:Q479040 "Amt Breitenburg" "deutschland/schleswig-holstein/kreis-steinburg/amt-breitenburg" "0")
      (wd:Q479401 "Amt Horst-Herzhorn" "deutschland/schleswig-holstein/kreis-steinburg/amt-horst-herzhorn" "0")
      (wd:Q430368 "Amt Itzehoe-Land" "deutschland/schleswig-holstein/kreis-steinburg/amt-itzehoe-land" "0")
      (wd:Q473895 "Amt Kellinghusen" "deutschland/schleswig-holstein/kreis-steinburg/amt-kellinghusen" "0")
      (wd:Q479519 "Amt Krempermarsch" "deutschland/schleswig-holstein/kreis-steinburg/amt-krempermarsch" "0")
      (wd:Q479888 "Amt Schenefeld" "deutschland/schleswig-holstein/kreis-steinburg/amt-schenefeld" "0")
      (wd:Q480149 "Amt Wilstermarsch" "deutschland/schleswig-holstein/kreis-steinburg/amt-wilstermarsch" "0")
    # (wd:Q3003 "Kreis Stormarn" "deutschland/schleswig-holstein/kreis-stormarn" "20")
      (wd:Q16104 "Ahrensburg" "deutschland/schleswig-holstein/kreis-stormarn/ahrensburg" "0")
      (wd:Q473175 "Gemeinde Ammersbek" "deutschland/schleswig-holstein/kreis-stormarn/gemeinde-ammersbek" "0")
      (wd:Q155226 "Bad Oldesloe" "deutschland/schleswig-holstein/kreis-stormarn/bad-oldesloe" "0")
      (wd:Q149921 "Bargteheide" "deutschland/schleswig-holstein/kreis-stormarn/bargteheide" "0")
      (wd:Q629424 "Gemeinde Barsbüttel" "deutschland/schleswig-holstein/kreis-stormarn/gemeinde-barsbuettel" "0")
      (wd:Q569696 "Glinde" "deutschland/schleswig-holstein/kreis-stormarn/glinde" "0")
      (wd:Q553192 "Gemeinde Großhansdorf" "deutschland/schleswig-holstein/kreis-stormarn/gemeinde-grosshansdorf" "0")
      (wd:Q560887 "Gemeinde Oststeinbek" "deutschland/schleswig-holstein/kreis-stormarn/gemeinde-oststeinbek" "0")
      (wd:Q516405 "Reinbek" "deutschland/schleswig-holstein/kreis-stormarn/reinbek" "0")
      (wd:Q539463 "Reinfeld" "deutschland/schleswig-holstein/kreis-stormarn/reinfeld" "0")
      (wd:Q478934 "Amt Bad Oldesloe-Land" "deutschland/schleswig-holstein/kreis-stormarn/amt-bad-oldesloe-land" "0")
      (wd:Q453918 "Amt Bargteheide-Land" "deutschland/schleswig-holstein/kreis-stormarn/amt-bargteheide-land" "0")
      (wd:Q479721 "Amt Nordstormarn" "deutschland/schleswig-holstein/kreis-stormarn/amt-nordstormarn" "0")
      (wd:Q315639 "Amt Siek" "deutschland/schleswig-holstein/kreis-stormarn/amt-siek" "0")
      (wd:Q455648 "Amt Trittau" "deutschland/schleswig-holstein/kreis-stormarn/amt-trittau" "0")
		}
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label {
	bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" .
  }
}