#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Deutschland mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape  ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number) {
    (wd:Q183 "Deutschland" "deutschland" "") 
		(wd:Q985 "Baden-Württemberg" "deutschland/baden-wuerttemberg" "")
		(wd:Q980 "Bayern" "deutschland/bayern" "")
		(wd:Q64 "Berlin" "deutschland/berlin" "")
		(wd:Q1208 "Brandenburg" "deutschland/brandenburg" "")
		(wd:Q1209 "Bremen" "deutschland/bremen" "954")
		(wd:Q1055 "Hamburg" "deutschland/hamburg" "")
		(wd:Q1199 "Hessen" "deutschland/hessen" "")
		(wd:Q1196 "Mecklenburg-Vorpommern" "deutschland/mecklenburg-vorpommern" "")
		(wd:Q1197 "Niedersachsen" "deutschland/niedersachsen" "4128")
		(wd:Q1198 "Nordrhein-Westfalen" "deutschland/nordrhein-westfalen" "")
		(wd:Q1200 "Rheinland-Pfalz" "deutschland/rheinland-pfalz" "")
		(wd:Q1201 "Saarland" "deutschland/saarland" "")
		(wd:Q1202 "Sachsen" "deutschland/sachsen" "")
		(wd:Q1206 "Sachsen-Anhalt" "deutschland/sachsen-anhalt" "")
			(wd:Q6061 "Altmarkkreis Salzwedel" "deutschland/sachsen-anhalt/altmarkkreis-salzwedel" "")
			(wd:Q6071 "Landkreis Anhalt-Bitterfeld" "deutschland/sachsen-anhalt/landkreis-anhalt-bitterfeld" "")
			(wd:Q6064 "Landkreis Börde" "deutschland/sachsen-anhalt/landkreis-boerde" "")
			(wd:Q6102 "Burgenlandkreis" "deutschland/sachsen-anhalt/burgenlandkreis" "")
			(wd:Q3828 "Dessau-Roßlau" "deutschland/sachsen-anhalt/dessau-rosslau" "")
			(wd:Q2814 "Halle (Saale)" "deutschland/sachsen-anhalt/halle-saale" "")
			(wd:Q6087 "Landkreis Harz" "deutschland/sachsen-anhalt/landkreis-harz" "")
			(wd:Q6068 "Landkreis Jerichower Land" "deutschland/sachsen-anhalt/landkreis-jerichower-land" "")
			(wd:Q1733 "Magdeburg" "deutschland/sachsen-anhalt/magdeburg" "")
			(wd:Q6092 "Landkreis Mansfeld-Südharz" "deutschland/sachsen-anhalt/landkreis-mansfeld-suedharz" "")
			(wd:Q6098 "Saalekreis" "deutschland/sachsen-anhalt/saalekreis" "")
			(wd:Q6081 "Salzlandkreis" "deutschland/sachsen-anhalt/salzlandkreis" "")
			(wd:Q6057 "Landkreis Stendal" "deutschland/sachsen-anhalt/landkreis-stendal" "")
			(wd:Q6075 "Landkreis Wittenberg" "deutschland/sachsen-anhalt/landkreis-wittenberg" "")
		(wd:Q1194 "Schleswig-Holstein" "deutschland/schleswig-holstein" "")
			(wd:Q2947 "Kreis Dithmarschen" "deutschland/schleswig-holstein/kreis-dithmarschen" "")
			(wd:Q3798 "Flensburg" "deutschland/schleswig-holstein/flensburg" "Die Einteilung der Stadtbezirke ist noch unklar")
			(wd:Q3000 "Kreis Herzogtum Lauenburg" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg" "")
			(wd:Q1707 "Kiel" "deutschland/schleswig-holstein/kiel" "Die Einteilung der Stadtbezirke ist noch unklar")
			(wd:Q2843 "Lübeck" "deutschland/schleswig-holstein/luebeck" "Die Einteilung der Stadtbezirke ist noch unklar")
			(wd:Q2937 "Kreis Nordfriesland" "deutschland/schleswig-holstein/kreis-nordfriesland" "")
			(wd:Q3879 "Neumünster" "deutschland/schleswig-holstein/neumuenster" "")
			(wd:Q2975 "Kreis Ostholstein" "deutschland/schleswig-holstein/kreis-ostholstein" "")
			(wd:Q3006 "Kreis Pinneberg" "deutschland/schleswig-holstein/kreis-pinneberg" "")
			(wd:Q2970 "Kreis Plön" "deutschland/schleswig-holstein/kreis-ploen" "")
			(wd:Q2967 "Kreis Rendsburg-Eckernförde" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde" "")
			(wd:Q2941 "Kreis Schleswig-Flensburg" "deutschland/schleswig-holstein/kreis-schleswig-flensburg" "")
			(wd:Q2980 "Kreis Segeberg" "deutschland/schleswig-holstein/kreis-segeberg" "")
			(wd:Q3011 "Kreis Steinburg" "deutschland/schleswig-holstein/kreis-steinburg" "")
			(wd:Q3003 "Kreis Stormarn" "deutschland/schleswig-holstein/kreis-stormarn" "")
		(wd:Q1205 "Thüringen" "deutschland/thueringen" "")
			(wd:Q7888 "Landkreis Altenburger Land" "deutschland/thueringen/landkreis-altenburger-land" "")
			(wd:Q7861 "Landkreis Eichsfeld" "deutschland/thueringen/landkreis-eichsfeld" "")
			(wd:Q1729 "Erfurt" "deutschland/thueringen/erfurt" "")
			(wd:Q3750 "Gera" "deutschland/thueringen/gera" "")
			(wd:Q7869 "Landkreis Gotha" "deutschland/thueringen/landkreis-gotha" "")
			(wd:Q7887 "Landkreis Greiz" "deutschland/thueringen/landkreis-greiz" "")
			(wd:Q7872 "Landkreis Hildburghausen" "deutschland/thueringen/landkreis-hildburghausen" "")
			(wd:Q7878 "Ilm-Kreis" "deutschland/thueringen/ilm-kreis" "")
			(wd:Q3150 "Jena" "deutschland/thueringen/jena" "")
			(wd:Q7862 "Kyffhäuserkreis" "deutschland/thueringen/landkreis-kyffhaeuserkreis" "")
			(wd:Q7858 "Landkreis Nordhausen" "deutschland/thueringen/landkreis-nordhausen" "")
			(wd:Q7884 "Saale-Holzland-Kreis" "deutschland/thueringen/saale-holzland-kreis" "")
			(wd:Q7883 "Saale-Orla-Kreis" "deutschland/thueringen/saale-orla-kreis" "")
			(wd:Q7882 "Landkreis Saalfeld-Rudolstadt" "deutschland/thueringen/landkreis-saalfeld-rudolstadt" "")
			(wd:Q7871 "Landkreis Schmalkalden-Meiningen" "deutschland/thueringen/landkreis-schmalkalden-meiningen" "")
			(wd:Q7865 "Landkreis Sömmerda" "deutschland/thueringen/landkreis-soemmerda" "")
			(wd:Q7875 "Landkreis Sonneberg" "deutschland/thueringen/landkreis-sonneberg" "")
			(wd:Q14891 "Suhl" "deutschland/thueringen/suhl" "")
			(wd:Q7864 "Unstrut-Hainich-Kreis" "deutschland/thueringen/unstrut-hainich-kreis" "")
			(wd:Q7866 "Wartburgkreis" "deutschland/thueringen/wartburgkreis" "")
			(wd:Q3955 "Weimar" "deutschland/thueringen/weimar" "")
			(wd:Q7879 "Landkreis Weimarer Land" "deutschland/thueringen/landkreis-weimarer-land" "")
		}
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label {
	bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" .
  }
}