#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Deutschland mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape  ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number) {
    (wd:Q183 "Deutschland" "deutschland" "")       
		(wd:Q985 "Baden-Württemberg" "deutschland/baden-wuerttemberg" "")
			(wd:Q8221 "Alb-Donau-Kreis" "deutschland/baden-wuerttemberg/alb-donau-kreis" "")
			(wd:Q4100 "Baden-Baden" "deutschland/baden-wuerttemberg/baden-baden" "")
			(wd:Q8223 "Landkreis Biberach" "deutschland/baden-wuerttemberg/landkreis-biberach" "")
			(wd:Q8536 "Landkreis Böblingen" "deutschland/baden-wuerttemberg/landkreis-boeblingen" "")
			(wd:Q8228 "Bodenseekreis" "deutschland/baden-wuerttemberg/bodenseekreis" "")
			(wd:Q8195 "Landkreis Breisgau-Hochschwarzwald" "deutschland/baden-wuerttemberg/landkreis-breisgau-hochschwarzwald" "")
			(wd:Q8186 "Landkreis Calw" "deutschland/baden-wuerttemberg/landkreis-calw" "")
			(wd:Q8193 "Landkreis Emmendingen" "deutschland/baden-wuerttemberg/landkreis-emmendingen" "")
			(wd:Q8184 "Enzkreis" "deutschland/baden-wuerttemberg/enzkreis" "")
			(wd:Q8533 "Landkreis Esslingen" "deutschland/baden-wuerttemberg/landkreis-esslingen" "")
			(wd:Q2833 "Freiburg im Breisgau" "deutschland/baden-wuerttemberg/freiburg-im-breisgau" "")
			(wd:Q8189 "Landkreis Freudenstadt" "deutschland/baden-wuerttemberg/landkreis-freudenstadt" "")
			(wd:Q8525 "Landkreis Göppingen" "deutschland/baden-wuerttemberg/landkreis-goeppingen" "")
			(wd:Q2966 "Heidelberg" "deutschland/baden-wuerttemberg/heidelberg" "")
			(wd:Q8523 "Landkreis Heidenheim" "deutschland/baden-wuerttemberg/landkreis-heidenheim" "")
			(wd:Q715 "Heilbronn" "deutschland/baden-wuerttemberg/heilbronn" "")
			(wd:Q7166 "Landkreis Heilbronn" "deutschland/baden-wuerttemberg/landkreis-heilbronn" "")
			(wd:Q8518 "Hohenlohekreis" "deutschland/baden-wuerttemberg/hohenlohekreis" "")
			(wd:Q1040 "Karlsruhe" "deutschland/baden-wuerttemberg/karlsruhe" "")
			(wd:Q8178 "Landkreis Karlsruhe" "deutschland/baden-wuerttemberg/landkreis-karlsruhe" "")
			(wd:Q8206 "Landkreis Konstanz" "deutschland/baden-wuerttemberg/landkreis-konstanz" "")
			(wd:Q8198 "Landkreis Lörrach" "deutschland/baden-wuerttemberg/landkreis-loerrach" "")
			(wd:Q8541 "Landkreis Ludwigsburg" "deutschland/baden-wuerttemberg/landkreis-ludwigsburg" "")
			(wd:Q8517 "Main-Tauber-Kreis" "deutschland/baden-wuerttemberg/main-tauber-kreis" "")
			(wd:Q2119 "Mannheim" "deutschland/baden-wuerttemberg/mannheim" "")
			(wd:Q8174 "Neckar-Odenwald-Kreis" "deutschland/baden-wuerttemberg/neckar-odenwald-kreis" "")
			(wd:Q8191 "Ortenaukreis" "deutschland/baden-wuerttemberg/ortenaukreis" "")
			(wd:Q8522 "Ostalbkreis" "deutschland/baden-wuerttemberg/ostalbkreis" "")
			(wd:Q3046 "Pforzheim" "deutschland/baden-wuerttemberg/pforzheim" "")
			(wd:Q8182 "Landkreis Rastatt" "deutschland/baden-wuerttemberg/landkreis-rastatt" "")
			(wd:Q8225 "Landkreis Ravensburg" "deutschland/baden-wuerttemberg/landkreis-ravensburg" "")
			(wd:Q8528 "Rems-Murr-Kreis" "deutschland/baden-wuerttemberg/rems-murr-kreis" "")
			(wd:Q8217 "Landkreis Reutlingen" "deutschland/baden-wuerttemberg/landkreis-reutlingen" "")
			(wd:Q8177 "Rhein-Neckar-Kreis" "deutschland/baden-wuerttemberg/rhein-neckar-kreis" "")
			(wd:Q8211 "Landkreis Rottweil" "deutschland/baden-wuerttemberg/landkreis-rottweil" "")
			(wd:Q8520 "Landkreis Schwäbisch Hall" "deutschland/baden-wuerttemberg/landkreis-schwaebisch-hall" "")
			(wd:Q8203 "Schwarzwald-Baar-Kreis" "deutschland/baden-wuerttemberg/schwarzwald-baar-kreis" "")
			(wd:Q8230 "Landkreis Sigmaringen" "deutschland/baden-wuerttemberg/landkreis-sigmaringen" "")
			(wd:Q1022 "Stuttgart" "deutschland/baden-wuerttemberg/stuttgart" "")
			(wd:Q8214 "Landkreis Tübingen" "deutschland/baden-wuerttemberg/landkreis-tuebingen" "")
			(wd:Q8208 "Landkreis Tuttlingen" "deutschland/baden-wuerttemberg/landkreis-tuttlingen" "")
			(wd:Q3012 "Ulm" "deutschland/baden-wuerttemberg/ulm" "")
			(wd:Q8200 "Landkreis Waldshut" "deutschland/baden-wuerttemberg/landkreis-waldshut" "")
			(wd:Q8233 "Zollernalbkreis" "deutschland/baden-wuerttemberg/zollernalbkreis" "")
		(wd:Q980 "Bayern" "deutschland/bayern" "")
			(wd:Q10415 "Landkreis Aichach-Friedberg" "deutschland/bayern/landkreis-aichach-friedberg" "")
			(wd:Q10533 "Landkreis Altötting" "deutschland/bayern/landkreis-altoetting" "")
			(wd:Q7042 "Amberg" "deutschland/bayern/amberg" "")
			(wd:Q10421 "Landkreis Amberg-Sulzbach" "deutschland/bayern/landkreis-amberg-sulzbach" "")
			(wd:Q14859 "Ansbach" "deutschland/bayern/ansbach" "")
			(wd:Q10454 "Landkreis Ansbach" "deutschland/bayern/landkreis-ansbach" "")
			(wd:Q3942 "Aschaffenburg" "deutschland/bayern/aschaffenburg" "")
			(wd:Q10471 "Landkreis Aschaffenburg" "deutschland/bayern/landkreis-aschaffenburg" "")
			(wd:Q2749 "Augsburg" "deutschland/bayern/augsburg" "")
			(wd:Q10414 "Landkreis Augsburg" "deutschland/bayern/landkreis-augsburg" "")
			(wd:Q10466 "Landkreis Bad Kissingen" "deutschland/bayern/landkreis-bad-kissingen" "")
			(wd:Q10522 "Landkreis Bad Tölz-Wolfratshausen" "deutschland/bayern/landkreis-bad-toelz-wolfratshausen" "")
			(wd:Q3936 "Bamberg" "deutschland/bayern/bamberg" "")
			(wd:Q10444 "Landkreis Bamberg" "deutschland/bayern/landkreis-bamberg" "")
			(wd:Q3923 "Bayreuth" "deutschland/bayern/bayreuth" "")
			(wd:Q10439 "Landkreis Bayreuth" "deutschland/bayern/landkreis-bayreuth" "")
			(wd:Q10530 "Landkreis Berchtesgadener Land" "deutschland/bayern/landkreis-berchtesgadener-land" "")
			(wd:Q10424 "Landkreis Cham" "deutschland/bayern/landkreis-cham" "")
			(wd:Q14821 "Coburg" "deutschland/bayern/coburg" "")
			(wd:Q10440 "Landkreis Coburg" "deutschland/bayern/landkreis-coburg" "")
			(wd:Q10500 "Landkreis Dachau" "deutschland/bayern/landkreis-dachau" "")
			(wd:Q10485 "Landkreis Deggendorf" "deutschland/bayern/landkreis-deggendorf" "")
			(wd:Q10417 "Landkreis Dillingen an der Donau" "deutschland/bayern/landkreis-dillingen-an-der-donau" "")
			(wd:Q10480 "Landkreis Dingolfing-Landau" "deutschland/bayern/landkreis-dingolfing-landau" "")
			(wd:Q10418 "Landkreis Donau-Ries" "deutschland/bayern/landkreis-donau-ries" "")
			(wd:Q10541 "Landkreis Ebersberg" "deutschland/bayern/landkreis-ebersberg" "")
			(wd:Q10491 "Landkreis Eichstätt" "deutschland/bayern/landkreis-eichstaett" "")
			(wd:Q10539 "Landkreis Erding" "deutschland/bayern/landkreis-erding" "")
			(wd:Q3126 "Erlangen" "deutschland/bayern/erlangen" "")
			(wd:Q10447 "Landkreis Erlangen-Höchstadt" "deutschland/bayern/landkreis-erlangen-hoechstadt" "")
			(wd:Q10445 "Landkreis Forchheim" "deutschland/bayern/landkreis-forchheim" "")
			(wd:Q10497 "Landkreis Freising" "deutschland/bayern/landkreis-freising" "")
			(wd:Q10487 "Landkreis Freyung-Grafenau" "deutschland/bayern/landkreis-freyung-grafenau" "")
			(wd:Q10502 "Landkreis Fürstenfeldbruck" "deutschland/bayern/landkreis-fuerstenfeldbruck" "")
			(wd:Q3075 "Fürth" "deutschland/bayern/fuerth" "")
			(wd:Q10455 "Landkreis Fürth" "deutschland/bayern/landkreis-fuerth" "")
			(wd:Q10518 "Landkreis Garmisch-Partenkirchen" "deutschland/bayern/landkreis-garmisch-partenkirchen" "")
			(wd:Q10412 "Landkreis Günzburg" "deutschland/bayern/landkreis-guenzburg" "")
			(wd:Q10462 "Landkreis Haßberge" "deutschland/bayern/landkreis-hassberge" "")
			(wd:Q6938 "Hof (Saale)" "deutschland/bayern/hof-saale" "")
			(wd:Q10431 "Landkreis Hof" "deutschland/bayern/landkreis-hof" "")
			(wd:Q3004 "Ingolstadt" "deutschland/bayern/ingolstadt" "")
			(wd:Q14805 "Kaufbeuren" "deutschland/bayern/kaufbeuren" "")
			(wd:Q10474 "Landkreis Kelheim" "deutschland/bayern/landkreis-kelheim" "")
			(wd:Q3994 "Kempten (Allgäu)" "deutschland/bayern/kempten-allgaeu" "")
			(wd:Q10459 "Landkreis Kitzingen" "deutschland/bayern/landkreis-kitzingen" "")
			(wd:Q10434 "Landkreis Kronach" "deutschland/bayern/landkreis-kronach" "")
			(wd:Q10436 "Landkreis Kulmbach" "deutschland/bayern/landkreis-kulmbach" "")
			(wd:Q10507 "Landkreis Landsberg am Lech" "deutschland/bayern/landkreis-landsberg-am-lech" "")
			(wd:Q3974 "Landshut" "deutschland/bayern/landshut" "")
			(wd:Q10475 "Landkreis Landshut" "deutschland/bayern/landkreis-landshut" "")
			(wd:Q10442 "Landkreis Lichtenfels" "deutschland/bayern/landkreis-lichtenfels" "")
			(wd:Q10401 "Landkreis Lindau (Bodensee)" "deutschland/bayern/landkreis-lindau-bodensee" "")
			(wd:Q10469 "Landkreis Main-Spessart" "deutschland/bayern/landkreis-main-spessart" "")
			(wd:Q14825 "Memmingen" "deutschland/bayern/memmingen" "")
			(wd:Q10523 "Landkreis Miesbach" "deutschland/bayern/landkreis-miesbach" "")
			(wd:Q10472 "Landkreis Miltenberg" "deutschland/bayern/landkreis-miltenberg" "")
			(wd:Q10537 "Landkreis Mühldorf am Inn" "deutschland/bayern/landkreis-muehldorf-am-inn" "")
			(wd:Q1726 "München" "deutschland/bayern/muenchen" "")
			(wd:Q10544 "Landkreis München" "deutschland/bayern/landkreis-muenchen" "")
			(wd:Q10493 "Landkreis Neuburg-Schrobenhausen" "deutschland/bayern/landkreis-neuburg-schrobenhausen" "")
			(wd:Q10427 "Landkreis Neumarkt in der Oberpfalz" "deutschland/bayern/landkreis-neumarkt-in-der-oberpfalz" "")
			(wd:Q10456 "Landkreis Neustadt an der Aisch-Bad Windsheim" "deutschland/bayern/landkreis-neustadt-an-der-aisch-bad-windsheim" "")
			(wd:Q10420 "Landkreis Neustadt an der Waldnaab" "deutschland/bayern/landkreis-neustadt-an-der-waldnaab" "")
			(wd:Q10410 "Landkreis Neu-Ulm" "deutschland/bayern/landkreis-neu-ulm" "")
			(wd:Q2090 "Nürnberg" "deutschland/bayern/nuernberg" "")
			(wd:Q10449 "Landkreis Nürnberger Land" "deutschland/bayern/landkreis-nuernberger-land" "")
			(wd:Q10402 "Landkreis Oberallgäu" "deutschland/bayern/landkreis-oberallgaeu" "")
			(wd:Q10405 "Landkreis Ostallgäu" "deutschland/bayern/landkreis-ostallgaeu" "")
			(wd:Q4190 "Passau" "deutschland/bayern/passau" "")
			(wd:Q10489 "Landkreis Passau" "deutschland/bayern/landkreis-passau" "")
			(wd:Q10496 "Landkreis Pfaffenhofen an der Ilm" "deutschland/bayern/landkreis-pfaffenhofen-an-der-ilm" "")
			(wd:Q10483 "Landkreis Regen" "deutschland/bayern/landkreis-regen" "")
			(wd:Q2978 "Regensburg" "deutschland/bayern/regensburg" "")
			(wd:Q10429 "Landkreis Regensburg" "deutschland/bayern/landkreis-regensburg" "")
			(wd:Q10465 "Landkreis Rhön-Grabfeld" "deutschland/bayern/landkreis-rhoen-grabfeld" "")
			(wd:Q4007 "Rosenheim" "deutschland/bayern/rosenheim" "")
			(wd:Q10526 "Landkreis Rosenheim" "deutschland/bayern/landkreis-rosenheim" "")
			(wd:Q10451 "Landkreis Roth" "deutschland/bayern/landkreis-roth" "")
			(wd:Q10477 "Landkreis Rottal-Inn" "deutschland/bayern/landkreis-rottal-inn" "")
			(wd:Q14889 "Schwabach" "deutschland/bayern/schwabach" "")
			(wd:Q10423 "Landkreis Schwandorf" "deutschland/bayern/landkreis-schwandorf" "")
			(wd:Q4126 "Schweinfurt" "deutschland/bayern/schweinfurt" "")
			(wd:Q10461 "Landkreis Schweinfurt" "deutschland/bayern/landkreis-schweinfurt" "")
			(wd:Q10504 "Landkreis Starnberg" "deutschland/bayern/landkreis-starnberg" "")
			(wd:Q7027 "Straubing" "deutschland/bayern/straubing" "")
			(wd:Q10482 "Landkreis Straubing-Bogen" "deutschland/bayern/landkreis-straubing-bogen" "")
			(wd:Q10419 "Landkreis Tirschenreuth" "deutschland/bayern/landkreis-tirschenreuth" "")
			(wd:Q10528 "Landkreis Traunstein" "deutschland/bayern/landkreis-traunstein" "")
			(wd:Q10408 "Landkreis Unterallgäu" "deutschland/bayern/landkreis-unterallgaeu" "")
			(wd:Q14803 "Weiden in der Oberpfalz" "deutschland/bayern/weiden-in-der-oberpfalz" "")
			(wd:Q10516 "Landkreis Weilheim-Schongau" "deutschland/bayern/landkreis-weilheim-schongau" "")
			(wd:Q10453 "Landkreis Weißenburg-Gunzenhausen" "deutschland/bayern/landkreis-weissenburg-gunzenhausen" "")
			(wd:Q10432 "Landkreis Wunsiedel im Fichtelgebirge" "deutschland/bayern/landkreis-wunsiedel-im-fichtelgebirge" "")
			(wd:Q2999 "Würzburg" "deutschland/bayern/wuerzburg" "")
			(wd:Q10458 "Landkreis Würzburg" "deutschland/bayern/landkreis-wuerzburg" "")
		(wd:Q64 "Berlin" "deutschland/berlin" "")
			(wd:Q163966 "Mitte" "deutschland/berlin/mitte" "")
			(wd:Q158893 "Friedrichshain-Kreuzberg" "deutschland/berlin/friedrichshain-kreuzberg" "")
			(wd:Q163012 "Pankow" "deutschland/berlin/pankow" "")
			(wd:Q158095 "Charlottenburg-Wilmersdorf" "deutschland/berlin/charlottenburg-wilmersdorf" "")
			(wd:Q158083 "Spandau" "deutschland/berlin/spandau" "")
			(wd:Q158064 "Steglitz-Zehlendorf" "deutschland/berlin/steglitz-zehlendorf" "")
			(wd:Q158106 "Tempelhof-Schöneberg" "deutschland/berlin/tempelhof-schoeneberg" "")
			(wd:Q4071168 "Neukölln" "deutschland/berlin/neukoelln" "")
			(wd:Q158089 "Treptow-Köpenick" "deutschland/berlin/treptow-koepenick" "")
			(wd:Q119284 "Marzahn-Hellersdorf" "deutschland/berlin/marzahn-hellersdorf" "")
			(wd:Q329609 "Lichtenberg" "deutschland/berlin/lichtenberg" "")
			(wd:Q158876 "Reinickendorf" "deutschland/berlin/reinickendorf" "")
		(wd:Q1208 "Brandenburg" "deutschland/brandenburg" "")
			(wd:Q6115 "Landkreis Barnim" "deutschland/brandenburg/landkreis-arnim" "")
			(wd:Q3931 "Brandenburg an der Havel" "deutschland/brandenburg/brandenburg-an-der-havel" "")
			(wd:Q3214 "Cottbus" "deutschland/brandenburg/cottbus" "")
			(wd:Q6173 "Landkreis Dahme-Spreewald" "deutschland/brandenburg/landkreis-dahme-spreewald" "")
			(wd:Q6152 "Landkreis Elbe-Elster" "deutschland/brandenburg/landkreis-elbe-elster" "")
			(wd:Q4024 "Frankfurt (Oder)" "deutschland/brandenburg/frankfurt-oder" "")
			(wd:Q6139 "Landkreis Havelland" "deutschland/brandenburg/landkreis-havelland" "")
			(wd:Q6181 "Landkreis Märkisch-Oderland" "deutschland/brandenburg/landkreis-maerkisch-oderland" "")
			(wd:Q6119 "Landkreis Oberhavel" "deutschland/brandenburg/landkreis-oberhavel" "")
			(wd:Q6156 "Landkreis Oberspreewald-Lausitz" "deutschland/brandenburg/landkreis-oberspreewald-lausitz" "")
			(wd:Q6178 "Landkreis Oder-Spree" "deutschland/brandenburg/landkreis-oder-spree" "")
			(wd:Q6125 "Landkreis Ostprignitz-Ruppin" "deutschland/brandenburg/landkreis-ostprignitz-ruppin" "")
			(wd:Q1711 "Potsdam" "deutschland/brandenburg/potsdam" "")
			(wd:Q6142 "Landkreis Potsdam-Mittelmark" "deutschland/brandenburg/landkreis-potsdam-mittelmark" "")
			(wd:Q6132 "Landkreis Prignitz" "deutschland/brandenburg/landkreis-prignitz" "")
			(wd:Q6165 "Landkreis Spree-Neiße" "deutschland/brandenburg/landkreis-spree-neisse" "")
			(wd:Q6146 "Landkreis Teltow-Fläming" "deutschland/brandenburg/landkreis-teltow-flaeming" "")
			(wd:Q6109 "Landkreis Uckermark" "deutschland/brandenburg/landkreis-uckermark" "")
		(wd:Q1209 "Bremen" "deutschland/bremen" "954")
			(wd:Q17278534 "Bremen Mitte" "deutschland/bremen/mitte" "159")
			(wd:Q30145095 "Bremen Süd" "deutschland/bremen/sued" "116")
			(wd:Q30147400 "Bremen Ost" "deutschland/bremen/ost" "287")
			(wd:Q30147399 "Bremen West" "deutschland/bremen/west" "159")
			(wd:Q907314 "Bremen Nord" "deutschland/bremen/nord" "79")
			(wd:Q15627784 "Bremerhaven Nord" "deutschland/bremen/bremerhaven/nord" "0")
			(wd:Q15627783 "Bremerhaven Süd" "deutschland/bremen/bremerhaven/sued" "0")
		(wd:Q1055 "Hamburg" "deutschland/hamburg" "")
		(wd:Q1199 "Hessen" "deutschland/hessen" "")
		(wd:Q1196 "Mecklenburg-Vorpommern" "deutschland/mecklenburg-vorpommern" "")
		(wd:Q1197 "Niedersachsen" "deutschland/niedersachsen" "" "4128")
			(wd:Q5947 "Landkreis Ammerland" "deutschland/niedersachsen/landkreis-ammerland" "" "1")
				(wd:Q503471 "Gemeinde Apen" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-apen" "0")
				(wd:Q504526 "Gemeinde Bad Zwischenahn" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-bad-zwischenahn" "0")
				(wd:Q503410 "Gemeinde Edewecht" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-edewecht" "0")
				(wd:Q512640 "Gemeinde Rastede" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-rastede" "0")
				(wd:Q492360 "Westerstede" "deutschland/niedersachsen/landkreis-ammerland/westerstede" "0")
				(wd:Q503388 "Gemeinde Wiefelstede" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-wiefelstede" "1")
			(wd:Q5929 "Landkreis Aurich" "deutschland/niedersachsen/landkreis-aurich" "" "8")
			(wd:Q2773 "Braunschweig" "deutschland/niedersachsen/braunschweig" "414")
			(wd:Q5919 "Landkreis Celle" "deutschland/niedersachsen/landkreis-celle" "115")
			(wd:Q5945 "Landkreis Cloppenburg" "deutschland/niedersachsen/landkreis-cloppenburg" "41")
			(wd:Q5897 "Landkreis Cuxhaven" "deutschland/niedersachsen/landkreis-cuxhaven" "green" "51")
			(wd:Q3907 "Delmenhorst" "deutschland/niedersachsen/delmenhorst" "" "40")
			(wd:Q5956 "Landkreis Diepholz" "deutschland/niedersachsen/landkreis-diepholz" "" "44")
			(wd:Q4174 "Emden" "deutschland/niedersachsen/emden" "" "0")
			(wd:Q5936 "Landkreis Emsland" "deutschland/niedersachsen/landkreis-emsland" "" "199")
			(wd:Q5932 "Landkreis Friesland" "deutschland/niedersachsen/landkreis-friesland" "" "4")
			(wd:Q6040 "Landkreis Goslar" "deutschland/niedersachsen/landkreis-goslar" "63")
			(wd:Q6022 "Landkreis Göttingen" "deutschland/niedersachsen/landkreis-goettingen" "190")
			(wd:Q5939 "Landkreis Grafschaft Bentheim" "deutschland/niedersachsen/landkreis-grafschaft-bentheim" "159")
			(wd:Q5970 "Landkreis Hameln-Pyrmont" "deutschland/niedersachsen/landkreis-hameln-pyrmont" "137")
			(wd:Q5963 "Region Hannover " "deutschland/niedersachsen/region-hannover" "748")
			(wd:Q5907 "Landkreis Harburg" "deutschland/niedersachsen/landkreis-harburg" "27")
			(wd:Q5922 "Heidekreis" "deutschland/niedersachsen/heidekreis" "6")
			(wd:Q6047 "Landkreis Helmstedt" "deutschland/niedersachsen/landkreis-helmstedt" "74")
			(wd:Q5978 "Landkreis Hildesheim" "deutschland/niedersachsen/landkreis-hildesheim" "292")
			(wd:Q5973 "Landkreis Holzminden" "deutschland/niedersachsen/landkreis-holzminden" "38")
			(wd:Q5934 "Landkreis Leer" "deutschland/niedersachsen/landkreis-leer" "196")
			(wd:Q5913 "Landkreis Lüchow-Dannenberg" "deutschland/niedersachsen/landkreis-luechow-dannenberg" "18")
			(wd:Q5910 "Landkreis Lüneburg" "deutschland/niedersachsen/landkreis-lueneburg" "77")
			(wd:Q5958 "Landkreis Nienburg/Weser" "deutschland/niedersachsen/landkreis-nienburg-weser" "131")
			(wd:Q6018 "Landkreis Northeim" "deutschland/niedersachsen/landkreis-northeim" "127")
			(wd:Q2936 "Oldenburg (Oldb)" "deutschland/niedersachsen/oldenburg-oldb" "8")
				# (wd: "" "deutschland/niedersachsen/oldenburg-oldb/" "") Die Einteilung der Stadtbezirke ist noch offen
			(wd:Q5952 "Landkreis Oldenburg" "deutschland/niedersachsen/landkreis-oldenburg" "12")
			(wd:Q2916 "Osnabrück" "deutschland/niedersachsen/osnabrueck" "10")
				# (wd: "" "deutschland/niedersachsen/osnabrueck/" "") Die Einteilung der Stadtbezirke ist noch offen
			(wd:Q5940 "Landkreis Osnabrück" "deutschland/niedersachsen/landkreis-osnabrueck" "118")
			(wd:Q5926 "Landkreis Osterholz" "deutschland/niedersachsen/landkreis-osterholz" "64")
			(wd:Q6045 "Landkreis Peine" "deutschland/niedersachsen/landkreis-peine" "57")
			(wd:Q5923 "Landkreis Rotenbrug (Wümme)" "deutschland/niedersachsen/landkreis-rotenburg-wuemme" "43")
			(wd:Q3200 "Salzgitter" "deutschland/niedersachsen/salzgitter" "12")
			(wd:Q5966 "Landkreis Schaumburg" "deutschland/niedersachsen/landkreis-schaumburg" "0")
			(wd:Q5906 "Landkreis Stade" "deutschland/niedersachsen/landkreis-stade" "25")
			(wd:Q5915 "Landkreis Uelzen" "deutschland/niedersachsen/landkreis-uelzen" "17")
			(wd:Q5941 "Landkreis Vechta" "deutschland/niedersachsen/landkreis-vechta" "21")
			(wd:Q5927 "Landkreis Verden" "deutschland/niedersachsen/landkreis-verden" "232")
			(wd:Q5948 "Landkreis Wesermarsch" "deutschland/niedersachsen/landkreis-wesermarsch" "24")
			(wd:Q3857 "Wilhelmshaven" "deutschland/niedersachsen/wilhelmshaven" "20")
			(wd:Q5931 "Landkreis Wittmund" "deutschland/niedersachsen/landkreis-wittmund" "29")
			(wd:Q6041 "Landkreis Wolfenbüttel" "deutschland/niedersachsen/landkreis-wolfenbuettel" "11")
			(wd:Q3014 "Wolfsburg" "deutschland/niedersachsen/wolfsburg" "0")	
		(wd:Q1198 "Nordrhein-Westfalen" "deutschland/nordrhein-westfalen" "")
		(wd:Q1200 "Rheinland-Pfalz" "deutschland/rheinland-pfalz" "")
			(wd:Q8596 "Landkreis Ahrweiler" "deutschland/rheinland-pfalz/landkreis-ahrweiler" "")
			(wd:Q8608 "Landkreis Altenkirchen (Westerwald)" "deutschland/rheinland-pfalz/landkreis-altenkirchen-westerwald" "")
			(wd:Q8566 "Landkreis Alzey-Worms" "deutschland/rheinland-pfalz/landkreis-alzey-worms" "")
			(wd:Q8557 "Landkreis Bad Dürkheim" "deutschland/rheinland-pfalz/landkreis-bad-duerkheim" "")
			(wd:Q8572 "Landkreis Bad Kreuznach" "deutschland/rheinland-pfalz/landkreis-bad-kreuznach" "")
			(wd:Q8585 "Landkreis Bernkastel-Wittlich" "deutschland/rheinland-pfalz/landkreis-bernkastel-wittlich" "")
			(wd:Q8575 "Landkreis Birkenfeld" "deutschland/rheinland-pfalz/landkreis-birkenfeld" "")
			(wd:Q8590 "Landkreis Cochem-Zell" "deutschland/rheinland-pfalz/landkreis-cochem-zell" "")
			(wd:Q8564 "Donnersbergkreis" "deutschland/rheinland-pfalz/donnersbergkreis" "")
			(wd:Q8580 "Eifelkreis Bitburg-Prüm" "deutschland/rheinland-pfalz/eifelkreis-bitburg-pruem" "")
			(wd:Q6905 "Frankenthal (Pfalz)" "deutschland/rheinland-pfalz/frankenthal-pfalz" "")
			(wd:Q8543 "Landkreis Germersheim" "deutschland/rheinland-pfalz/landkreis-germersheim" "")
			(wd:Q3758 "Kaiserslautern" "deutschland/rheinland-pfalz/kaiserslautern" "")
			(wd:Q8559 "Landkreis Kaiserslautern" "deutschland/rheinland-pfalz/landkreis-kaiserslautern" "")
			(wd:Q3104 "Koblenz" "deutschland/rheinland-pfalz/koblenz" "")
			(wd:Q8562 "Landkreis Kusel" "deutschland/rheinland-pfalz/landkreis-kusel" "")
			(wd:Q7052 "Landau in der Pfalz" "deutschland/rheinland-pfalz/landau-in-der-pfalz" "")
			(wd:Q2910 "Ludwigshafen am Rhein" "deutschland/rheinland-pfalz/ludwigshafen-am-rhein" "") 
			(wd:Q1720 "Mainz" "deutschland/rheinland-pfalz/mainz" "")
			(wd:Q8569 "Landkreis Mainz-Bingen" "deutschland/rheinland-pfalz/landkreis-mainz-bingen" "")
			(wd:Q8593 "Landkreis Mayen-Koblenz" "deutschland/rheinland-pfalz/landkreis-mayen-koblenz" "")
			(wd:Q4149 "Neustadt an der Weinstraße" "deutschland/rheinland-pfalz/neustadt-an-der-weinstraße" "")
			(wd:Q8606 "Landkreis Neuwied" "deutschland/rheinland-pfalz/landkreis-neuwied" "")
			(wd:Q14849 "Pirmasens" "deutschland/rheinland-pfalz/pirmasens" "")
			(wd:Q8574 "Rhein-Hunsrück-Kreis" "deutschland/rheinland-pfalz/rhein-hunsrueck-kreis" "")
			(wd:Q8601 "Rhein-Lahn-Kreis" "deutschland/rheinland-pfalz/rhein-lahn-kreis" "")
			(wd:Q8554 "Rhein-Pfalz-Kreis" "deutschland/rheinland-pfalz/rhein-pfalz-kreis" "")
			(wd:Q6829 "Speyer" "deutschland/rheinland-pfalz/speyer" "")
			(wd:Q8551 "Landkreis Südliche Weinstraße" "deutschland/rheinland-pfalz/landkreis-suedliche-weinstrasse" "")
			(wd:Q8552 "Landkreis Südwestpfalz" "deutschland/rheinland-pfalz/landkreis-suedwestpfalz" "")
			(wd:Q3138 "Trier" "deutschland/rheinland-pfalz/trier" "")
			(wd:Q8579 "Landkreis Trier-Saarburg" "deutschland/rheinland-pfalz/landkreis-trier-saarburg" "")
			(wd:Q8583 "Landkreis Vulkaneifel" "deutschland/rheinland-pfalz/landkreis-vulkaneifel" "")
			(wd:Q8602 "Westerwaldkreis" "deutschland/rheinland-pfalz/westerwaldkreis" "")
			(wd:Q3852 "Worms" "deutschland/rheinland-pfalz/worms" "")
			(wd:Q16017 "Zweibrücken" "deutschland/rheinland-pfalz/zweibruecken" "")
		(wd:Q1201 "Saarland" "deutschland/saarland" "")
			(wd:Q6802 "Landkreis Merzig-Wadern" "deutschland/saarland/landkreis-merzig-wadern" "")
			(wd:Q6799 "Landkreis Neunkirchen" "deutschland/saarland/landkreis-neunkirchen" "")
			(wd:Q6805 "Regionalverband Saarbrücken" "deutschland/saarland/regionalverband-saarbruecken" "")
				(wd:Q1724 "Saarbrücken" "deutschland/saarland/regionalverband-saarbruecken/saarbruecken" "P3896 fehlt")
					(wd:Q20850653 "Mitte" "deutschland/saarland/regionalverband-saarbruecken/saarbruecken/mitte" "P3896 fehlt")
					(wd:Q20850634 "West" "deutschland/saarland/regionalverband-saarbruecken/saarbruecken/west" "P3896 fehlt")
					(wd:Q20850647 "Dudweiler" "deutschland/saarland/regionalverband-saarbruecken/saarbruecken/dudweiler" "P3896 fehlt")
					(wd:Q20850649 "Halberg" "deutschland/saarland/regionalverband-saarbruecken/saarbruecken/halberg" "P3896 fehlt")
			(wd:Q6794 "Landkreis Saarlouis" "deutschland/saarland/landkreis-saarlouis" "")
			(wd:Q6793 "Saarpfalz-Kreis" "deutschland/saarland/saarpfalz-kreis" "")
			(wd:Q6789 "Landkreis St. Wendel" "deutschland/saarland/landkreis-st-wendel" "")
		(wd:Q1202 "Sachsen" "deutschland/sachsen" "")
			(wd:Q571947 "Landkreis Bautzen" "deutschland/sachsen/landkreis-bautzen" "")
			(wd:Q2795 "Chemnitz" "deutschland/sachsen/chemnitz" "")
			(wd:Q1731 "Dresden" "deutschland/sachsen/dresden" "")
			(wd:Q6339 "Erzgebirgskreis" "deutschland/sachsen/erzgebirgskreis" "")
			(wd:Q6317 "Landkreis Görlitz" "deutschland/sachsen/landkreis-goerlitz" "")
			(wd:Q6308 "Landkreis Leipzig" "deutschland/sachsen/landkreis-leipzig" "")
			(wd:Q2079 "Leipzig" "deutschland/sachsen/leipzig" "")
			(wd:Q6313 "Landkreis Meißen" "deutschland/sachsen/landkreis-meissen" "")
			(wd:Q6328 "Landkreis Mittelsachsen" "deutschland/sachsen/landkreis-mittelsachsen" "")
			(wd:Q6301 "Landkreis Nordsachsen" "deutschland/sachsen/landkreis-nordsachsen" "")
			(wd:Q6323 "Landkreis Sächsische Schweiz-Osterzgebirge" "deutschland/sachsen/landkreis-saechsische-schweiz-osterzgebirge" "")
			(wd:Q6337 "Vogtlandkreis" "deutschland/sachsen/vogtlandkreis" "")
			(wd:Q6330 "Landkreis Zwickau" "deutschland/sachsen/landkreis-zwickau" "")
		(wd:Q1206 "Sachsen-Anhalt" "deutschland/sachsen-anhalt" "")
			(wd:Q6061 "Altmarkkreis Salzwedel" "deutschland/sachsen-anhalt/altmarkkreis-salzwedel" "")
			(wd:Q6071 "Landkreis Anhalt-Bitterfeld" "deutschland/sachsen-anhalt/landkreis-anhalt-bitterfeld" "")
			(wd:Q6064 "Landkreis Börde" "deutschland/sachsen-anhalt/landkreis-boerde" "")
			(wd:Q6102 "Burgenlandkreis" "deutschland/sachsen-anhalt/burgenlandkreis" "")
			(wd:Q3828 "Dessau-Roßlau" "deutschland/sachsen-anhalt/dessau-rosslau" "")
			(wd:Q2814 "Halle (Saale)" "deutschland/sachsen-anhalt/halle-saale" "")
			(wd:Q6087 "Landkreis Harz" "deutschland/sachsen-anhalt/landkreis-harz" "")
			(wd:Q6068 "Landkreis Jerichower Land" "deutschland/sachsen-anhalt/landkreis-jerichower-land" "")
			(wd:Q1733 "Magdeburg" "deutschland/sachsen-anhalt/magdeburg" "")
			(wd:Q6092 "Landkreis Mansfeld-Südharz" "deutschland/sachsen-anhalt/landkreis-mansfeld-suedharz" "")
			(wd:Q6098 "Saalekreis" "deutschland/sachsen-anhalt/saalekreis" "")
			(wd:Q6081 "Salzlandkreis" "deutschland/sachsen-anhalt/salzlandkreis" "")
			(wd:Q6057 "Landkreis Stendal" "deutschland/sachsen-anhalt/landkreis-stendal" "")
			(wd:Q6075 "Landkreis Wittenberg" "deutschland/sachsen-anhalt/landkreis-wittenberg" "")
		(wd:Q1194 "Schleswig-Holstein" "deutschland/schleswig-holstein" "")
			(wd:Q2947 "Kreis Dithmarschen" "deutschland/schleswig-holstein/kreis-dithmarschen" "")
			(wd:Q3798 "Flensburg" "deutschland/schleswig-holstein/flensburg" "Die Einteilung der Stadtbezirke ist noch unklar")
			(wd:Q3000 "Kreis Herzogtum Lauenburg" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg" "")
			(wd:Q1707 "Kiel" "deutschland/schleswig-holstein/kiel" "Die Einteilung der Stadtbezirke ist noch unklar")
			(wd:Q2843 "Lübeck" "deutschland/schleswig-holstein/luebeck" "Die Einteilung der Stadtbezirke ist noch unklar")
			(wd:Q2937 "Kreis Nordfriesland" "deutschland/schleswig-holstein/kreis-nordfriesland" "")
			(wd:Q3879 "Neumünster" "deutschland/schleswig-holstein/neumuenster" "")
			(wd:Q2975 "Kreis Ostholstein" "deutschland/schleswig-holstein/kreis-ostholstein" "")
			(wd:Q3006 "Kreis Pinneberg" "deutschland/schleswig-holstein/kreis-pinneberg" "")
			(wd:Q2970 "Kreis Plön" "deutschland/schleswig-holstein/kreis-ploen" "")
			(wd:Q2967 "Kreis Rendsburg-Eckernförde" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde" "")
			(wd:Q2941 "Kreis Schleswig-Flensburg" "deutschland/schleswig-holstein/kreis-schleswig-flensburg" "")
			(wd:Q2980 "Kreis Segeberg" "deutschland/schleswig-holstein/kreis-segeberg" "")
			(wd:Q3011 "Kreis Steinburg" "deutschland/schleswig-holstein/kreis-steinburg" "")
			(wd:Q3003 "Kreis Stormarn" "deutschland/schleswig-holstein/kreis-stormarn" "")
		(wd:Q1205 "Thüringen" "deutschland/thueringen" "")
			(wd:Q7888 "Landkreis Altenburger Land" "deutschland/thueringen/landkreis-altenburger-land" "")
			(wd:Q7861 "Landkreis Eichsfeld" "deutschland/thueringen/landkreis-eichsfeld" "")
			(wd:Q1729 "Erfurt" "deutschland/thueringen/erfurt" "")
			(wd:Q3750 "Gera" "deutschland/thueringen/gera" "")
			(wd:Q7869 "Landkreis Gotha" "deutschland/thueringen/landkreis-gotha" "")
			(wd:Q7887 "Landkreis Greiz" "deutschland/thueringen/landkreis-greiz" "")
			(wd:Q7872 "Landkreis Hildburghausen" "deutschland/thueringen/landkreis-hildburghausen" "")
			(wd:Q7878 "Ilm-Kreis" "deutschland/thueringen/ilm-kreis" "")
			(wd:Q3150 "Jena" "deutschland/thueringen/jena" "")
			(wd:Q7862 "Kyffhäuserkreis" "deutschland/thueringen/landkreis-kyffhaeuserkreis" "")
			(wd:Q7858 "Landkreis Nordhausen" "deutschland/thueringen/landkreis-nordhausen" "")
			(wd:Q7884 "Saale-Holzland-Kreis" "deutschland/thueringen/saale-holzland-kreis" "")
			(wd:Q7883 "Saale-Orla-Kreis" "deutschland/thueringen/saale-orla-kreis" "")
			(wd:Q7882 "Landkreis Saalfeld-Rudolstadt" "deutschland/thueringen/landkreis-saalfeld-rudolstadt" "")
			(wd:Q7871 "Landkreis Schmalkalden-Meiningen" "deutschland/thueringen/landkreis-schmalkalden-meiningen" "")
			(wd:Q7865 "Landkreis Sömmerda" "deutschland/thueringen/landkreis-soemmerda" "")
			(wd:Q7875 "Landkreis Sonneberg" "deutschland/thueringen/landkreis-sonneberg" "")
			(wd:Q14891 "Suhl" "deutschland/thueringen/suhl" "")
			(wd:Q7864 "Unstrut-Hainich-Kreis" "deutschland/thueringen/unstrut-hainich-kreis" "")
			(wd:Q7866 "Wartburgkreis" "deutschland/thueringen/wartburgkreis" "")
			(wd:Q3955 "Weimar" "deutschland/thueringen/weimar" "")
			(wd:Q7879 "Landkreis Weimarer Land" "deutschland/thueringen/landkreis-weimarer-land" "")
		}
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label {
	bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" .
  }
}