#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Deutschland mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape  ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number) {
    (wd:Q183 "Deutschland" "deutschland" "")       
		(wd:Q985 "Baden-Württemberg" "deutschland/baden-wuerttemberg" "")
		(wd:Q980 "Bayern" "deutschland/bayern" "")
		(wd:Q64 "Berlin" "deutschland/berlin" "")
		(wd:Q1208 "Brandenburg" "deutschland/brandenburg" "")
		(wd:Q1209 "Bremen" "deutschland/bremen" "954")
			(wd:Q17278534 "Bremen Mitte" "deutschland/bremen/mitte" "159")
			(wd:Q30145095 "Bremen Süd" "deutschland/bremen/sued" "116")
			(wd:Q30147400 "Bremen Ost" "deutschland/bremen/ost" "287")
			(wd:Q30147399 "Bremen West" "deutschland/bremen/west" "159")
			(wd:Q907314 "Bremen Nord" "deutschland/bremen/nord" "79")
			(wd:Q15627784 "Bremerhaven Nord" "deutschland/bremen/bremerhaven/nord" "0")
			(wd:Q15627783 "Bremerhaven Süd" "deutschland/bremen/bremerhaven/sued" "0")
		(wd:Q1055 "Hamburg" "deutschland/hamburg" "")
		(wd:Q1199 "Hessen" "deutschland/hessen" "")
		(wd:Q1196 "Mecklenburg-Vorpommern" "deutschland/mecklenburg-vorpommern" "")
		(wd:Q1197 "Niedersachsen" "deutschland/niedersachsen" "" "4128")
			(wd:Q5947 "Landkreis Ammerland" "deutschland/niedersachsen/landkreis-ammerland" "" "1")
				(wd:Q503471 "Gemeinde Apen" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-apen" "0")
				(wd:Q504526 "Gemeinde Bad Zwischenahn" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-bad-zwischenahn" "0")
				(wd:Q503410 "Gemeinde Edewecht" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-edewecht" "0")
				(wd:Q512640 "Gemeinde Rastede" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-rastede" "0")
				(wd:Q492360 "Westerstede" "deutschland/niedersachsen/landkreis-ammerland/westerstede" "0")
				(wd:Q503388 "Gemeinde Wiefelstede" "deutschland/niedersachsen/landkreis-ammerland/gemeinde-wiefelstede" "1")
			(wd:Q5929 "Landkreis Aurich" "deutschland/niedersachsen/landkreis-aurich" "" "8")
			(wd:Q2773 "Braunschweig" "deutschland/niedersachsen/braunschweig" "414")
			(wd:Q5919 "Landkreis Celle" "deutschland/niedersachsen/landkreis-celle" "115")
			(wd:Q5945 "Landkreis Cloppenburg" "deutschland/niedersachsen/landkreis-cloppenburg" "41")
			(wd:Q5897 "Landkreis Cuxhaven" "deutschland/niedersachsen/landkreis-cuxhaven" "green" "51")
			(wd:Q3907 "Delmenhorst" "deutschland/niedersachsen/delmenhorst" "" "40")
			(wd:Q5956 "Landkreis Diepholz" "deutschland/niedersachsen/landkreis-diepholz" "" "44")
			(wd:Q4174 "Emden" "deutschland/niedersachsen/emden" "" "0")
			(wd:Q5936 "Landkreis Emsland" "deutschland/niedersachsen/landkreis-emsland" "" "199")
			(wd:Q5932 "Landkreis Friesland" "deutschland/niedersachsen/landkreis-friesland" "" "4")
			(wd:Q6040 "Landkreis Goslar" "deutschland/niedersachsen/landkreis-goslar" "63")
			(wd:Q6022 "Landkreis Göttingen" "deutschland/niedersachsen/landkreis-goettingen" "190")
			(wd:Q5939 "Landkreis Grafschaft Bentheim" "deutschland/niedersachsen/landkreis-grafschaft-bentheim" "159")
			(wd:Q5970 "Landkreis Hameln-Pyrmont" "deutschland/niedersachsen/landkreis-hameln-pyrmont" "137")
			(wd:Q5963 "Region Hannover " "deutschland/niedersachsen/region-hannover" "748")
			(wd:Q5907 "Landkreis Harburg" "deutschland/niedersachsen/landkreis-harburg" "27")
			(wd:Q5922 "Heidekreis" "deutschland/niedersachsen/heidekreis" "6")
			(wd:Q6047 "Landkreis Helmstedt" "deutschland/niedersachsen/landkreis-helmstedt" "74")
			(wd:Q5978 "Landkreis Hildesheim" "deutschland/niedersachsen/landkreis-hildesheim" "292")
			(wd:Q5973 "Landkreis Holzminden" "deutschland/niedersachsen/landkreis-holzminden" "38")
			(wd:Q5934 "Landkreis Leer" "deutschland/niedersachsen/landkreis-leer" "196")
			(wd:Q5913 "Landkreis Lüchow-Dannenberg" "deutschland/niedersachsen/landkreis-luechow-dannenberg" "18")
			(wd:Q5910 "Landkreis Lüneburg" "deutschland/niedersachsen/landkreis-lueneburg" "77")
			(wd:Q5958 "Landkreis Nienburg/Weser" "deutschland/niedersachsen/landkreis-nienburg-weser" "131")
			(wd:Q6018 "Landkreis Northeim" "deutschland/niedersachsen/landkreis-northeim" "127")
			(wd:Q2936 "Oldenburg (Oldb)" "deutschland/niedersachsen/oldenburg-oldb" "8")
				# (wd: "" "deutschland/niedersachsen/oldenburg-oldb/" "") Die Einteilung der Stadtbezirke ist noch offen
			(wd:Q5952 "Landkreis Oldenburg" "deutschland/niedersachsen/landkreis-oldenburg" "12")
			(wd:Q2916 "Osnabrück" "deutschland/niedersachsen/osnabrueck" "10")
				# (wd: "" "deutschland/niedersachsen/osnabrueck/" "") Die Einteilung der Stadtbezirke ist noch offen
			(wd:Q5940 "Landkreis Osnabrück" "deutschland/niedersachsen/landkreis-osnabrueck" "118")
			(wd:Q5926 "Landkreis Osterholz" "deutschland/niedersachsen/landkreis-osterholz" "64")
			(wd:Q6045 "Landkreis Peine" "deutschland/niedersachsen/landkreis-peine" "57")
			(wd:Q5923 "Landkreis Rotenbrug (Wümme)" "deutschland/niedersachsen/landkreis-rotenburg-wuemme" "43")
			(wd:Q3200 "Salzgitter" "deutschland/niedersachsen/salzgitter" "12")
			(wd:Q5966 "Landkreis Schaumburg" "deutschland/niedersachsen/landkreis-schaumburg" "0")
			(wd:Q5906 "Landkreis Stade" "deutschland/niedersachsen/landkreis-stade" "25")
			(wd:Q5915 "Landkreis Uelzen" "deutschland/niedersachsen/landkreis-uelzen" "17")
			(wd:Q5941 "Landkreis Vechta" "deutschland/niedersachsen/landkreis-vechta" "21")
			(wd:Q5927 "Landkreis Verden" "deutschland/niedersachsen/landkreis-verden" "232")
			(wd:Q5948 "Landkreis Wesermarsch" "deutschland/niedersachsen/landkreis-wesermarsch" "24")
			(wd:Q3857 "Wilhelmshaven" "deutschland/niedersachsen/wilhelmshaven" "20")
			(wd:Q5931 "Landkreis Wittmund" "deutschland/niedersachsen/landkreis-wittmund" "29")
			(wd:Q6041 "Landkreis Wolfenbüttel" "deutschland/niedersachsen/landkreis-wolfenbuettel" "11")
			(wd:Q3014 "Wolfsburg" "deutschland/niedersachsen/wolfsburg" "0")	
		(wd:Q1198 "Nordrhein-Westfalen" "deutschland/nordrhein-westfalen" "")
		(wd:Q1200 "Rheinland-Pfalz" "deutschland/rheinland-pfalz" "")
		(wd:Q1201 "Saarland" "deutschland/saarland" "")
		(wd:Q1202 "Sachsen" "deutschland/sachsen" "")
		(wd:Q1206 "Sachsen-Anhalt" "deutschland/sachsen-anhalt" "")
		(wd:Q1194 "Schleswig-Holstein" "deutschland/schleswig-holstein" "")
			(wd:Q2947 "Kreis Dithmarschen" "deutschland/schleswig-holstein/kreis-dithmarschen" "")
			(wd:Q3798 "Flensburg" "deutschland/schleswig-holstein/flensburg" "Die Einteilung der Stadtbezirke ist noch unklar")
			(wd:Q3000 "Kreis Herzogtum Lauenburg" "deutschland/schleswig-holstein/kreis-herzogtum-lauenburg" "")
			(wd:Q1707 "Kiel" "deutschland/schleswig-holstein/kiel" "Die Einteilung der Stadtbezirke ist noch unklar")
			(wd:Q2843 "Lübeck" "deutschland/schleswig-holstein/luebeck" "Die Einteilung der Stadtbezirke ist noch unklar")
			(wd:Q2937 "Kreis Nordfriesland" "deutschland/schleswig-holstein/kreis-nordfriesland" "")
			(wd:Q3879 "Neumünster" "deutschland/schleswig-holstein/neumuenster" "")
			(wd:Q2975 "Kreis Ostholstein" "deutschland/schleswig-holstein/kreis-ostholstein" "")
			(wd:Q3006 "Kreis Pinneberg" "deutschland/schleswig-holstein/kreis-pinneberg" "")
			(wd:Q2970 "Kreis Plön" "deutschland/schleswig-holstein/kreis-ploen" "")
			(wd:Q2967 "Kreis Rendsburg-Eckernförde" "deutschland/schleswig-holstein/kreis-rendsburg-eckernfoerde" "")
			(wd:Q2941 "Kreis Schleswig-Flensburg" "deutschland/schleswig-holstein/kreis-schleswig-flensburg" "")
			(wd:Q2980 "Kreis Segeberg" "deutschland/schleswig-holstein/kreis-segeberg" "")
			(wd:Q3011 "Kreis Steinburg" "deutschland/schleswig-holstein/kreis-steinburg" "")
			(wd:Q3003 "Kreis Stormarn" "deutschland/schleswig-holstein/kreis-stormarn" "")
		(wd:Q1205 "Thüringen" "deutschland/thueringen" "")
			(wd:Q7888 "Landkreis Altenburger Land" "deutschland/thueringen/landkreis-altenburger-land" "")
			(wd:Q7861 "Landkreis Eichsfeld" "deutschland/thueringen/landkreis-eichsfeld" "")
			(wd:Q1729 "Erfurt" "deutschland/thueringen/erfurt" "")
			(wd:Q3750 "Gera" "deutschland/thueringen/gera" "")
			(wd:Q7869 "Landkreis Gotha" "deutschland/thueringen/landkreis-gotha" "")
			(wd:Q7887 "Landkreis Greiz" "deutschland/thueringen/landkreis-greiz" "")
			(wd:Q7872 "Landkreis Hildburghausen" "deutschland/thueringen/landkreis-hildburghausen" "")
			(wd:Q7878 "Ilm-Kreis" "deutschland/thueringen/ilm-kreis" "")
			(wd:Q3150 "Jena" "deutschland/thueringen/jena" "")
			(wd:Q7862 "Kyffhäuserkreis" "deutschland/thueringen/landkreis-kyffhaeuserkreis" "")
			(wd:Q7858 "Landkreis Nordhausen" "deutschland/thueringen/landkreis-nordhausen" "")
			(wd:Q7884 "Saale-Holzland-Kreis" "deutschland/thueringen/saale-holzland-kreis" "")
			(wd:Q7883 "Saale-Orla-Kreis" "deutschland/thueringen/saale-orla-kreis" "")
			(wd:Q7882 "Landkreis Saalfeld-Rudolstadt" "deutschland/thueringen/landkreis-saalfeld-rudolstadt" "")
			(wd:Q7871 "Landkreis Schmalkalden-Meiningen" "deutschland/thueringen/landkreis-schmalkalden-meiningen" "")
			(wd:Q7865 "Landkreis Sömmerda" "deutschland/thueringen/landkreis-soemmerda" "")
			(wd:Q7875 "Landkreis Sonneberg" "deutschland/thueringen/landkreis-sonneberg" "")
			(wd:Q14891 "Suhl" "deutschland/thueringen/suhl" "")
			(wd:Q7864 "Unstrut-Hainich-Kreis" "deutschland/thueringen/unstrut-hainich-kreis" "")
			(wd:Q7866 "Wartburgkreis" "deutschland/thueringen/wartburgkreis" "")
			(wd:Q3955 "Weimar" "deutschland/thueringen/weimar" "")
			(wd:Q7879 "Landkreis Weimarer Land" "deutschland/thueringen/landkreis-weimarer-land" "")
		}
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label {
	bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" .
  }
}