#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Baden-Württemberg mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape ?number ?rgb
WHERE 
{
  VALUES (?id ?name ?safeURL ?number) 
  {   
    (wd:Q8221 "Alb-Donau-Kreis" "deutschland/baden-wuerttemberg/alb-donau-kreis" "")
    (wd:Q4100 "Baden-Baden" "deutschland/baden-wuerttemberg/baden-baden" "")
    (wd:Q8223 "Landkreis Biberach" "deutschland/baden-wuerttemberg/landkreis-biberach" "")
    (wd:Q8536 "Landkreis Böblingen" "deutschland/baden-wuerttemberg/landkreis-boeblingen" "")
    (wd:Q8228 "Bodenseekreis" "deutschland/baden-wuerttemberg/bodenseekreis" "")
    (wd:Q8195 "Landkreis Breisgau-Hochschwarzwald" "deutschland/baden-wuerttemberg/landkreis-breisgau-hochschwarzwald" "")
    (wd:Q8186 "Landkreis Calw" "deutschland/baden-wuerttemberg/landkreis-calw" "")
    (wd:Q8193 "Landkreis Emmendingen" "deutschland/baden-wuerttemberg/landkreis-emmendingen" "")
    (wd:Q8184 "Enzkreis" "deutschland/baden-wuerttemberg/enzkreis" "")
    (wd:Q8533 "Landkreis Esslingen" "deutschland/baden-wuerttemberg/landkreis-esslingen" "")
    (wd:Q2833 "Freiburg im Breisgau" "deutschland/baden-wuerttemberg/freiburg-im-breisgau" "")
    (wd:Q8189 "Landkreis Freudenstadt" "deutschland/baden-wuerttemberg/landkreis-freudenstadt" "")
    (wd:Q8525 "Landkreis Göppingen" "deutschland/baden-wuerttemberg/landkreis-goeppingen" "")
    (wd:Q2966 "Heidelberg" "deutschland/baden-wuerttemberg/heidelberg" "")
    (wd:Q8523 "Landkreis Heidenheim" "deutschland/baden-wuerttemberg/landkreis-heidenheim" "")
    (wd:Q715 "Heilbronn" "deutschland/baden-wuerttemberg/heilbronn" "")
    (wd:Q7166 "Landkreis Heilbronn" "deutschland/baden-wuerttemberg/landkreis-heilbronn" "")
    (wd:Q8518 "Hohenlohekreis" "deutschland/baden-wuerttemberg/hohenlohekreis" "")
    (wd:Q1040 "Karlsruhe" "deutschland/baden-wuerttemberg/karlsruhe" "")
    (wd:Q8178 "Landkreis Karlsruhe" "deutschland/baden-wuerttemberg/landkreis-karlsruhe" "")
    (wd:Q8206 "Landkreis Konstanz" "deutschland/baden-wuerttemberg/landkreis-konstanz" "")
    (wd:Q8198 "Landkreis Lörrach" "deutschland/baden-wuerttemberg/landkreis-loerrach" "")
    (wd:Q8541 "Landkreis Ludwigsburg" "deutschland/baden-wuerttemberg/landkreis-ludwigsburg" "")
    (wd:Q8517 "Main-Tauber-Kreis" "deutschland/baden-wuerttemberg/main-tauber-kreis" "")
    (wd:Q2119 "Mannheim" "deutschland/baden-wuerttemberg/mannheim" "")
    (wd:Q8174 "Neckar-Odenwald-Kreis" "deutschland/baden-wuerttemberg/neckar-odenwald-kreis" "")
    (wd:Q8191 "Ortenaukreis" "deutschland/baden-wuerttemberg/ortenaukreis" "")
    (wd:Q8522 "Ostalbkreis" "deutschland/baden-wuerttemberg/ostalbkreis" "")
    (wd:Q3046 "Pforzheim" "deutschland/baden-wuerttemberg/pforzheim" "")
    (wd:Q8182 "Landkreis Rastatt" "deutschland/baden-wuerttemberg/landkreis-rastatt" "")
    (wd:Q8225 "Landkreis Ravensburg" "deutschland/baden-wuerttemberg/landkreis-ravensburg" "")
    (wd:Q8528 "Rems-Murr-Kreis" "deutschland/baden-wuerttemberg/rems-murr-kreis" "")
    (wd:Q8217 "Landkreis Reutlingen" "deutschland/baden-wuerttemberg/landkreis-reutlingen" "")
    (wd:Q8177 "Rhein-Neckar-Kreis" "deutschland/baden-wuerttemberg/rhein-neckar-kreis" "")
    (wd:Q8211 "Landkreis Rottweil" "deutschland/baden-wuerttemberg/landkreis-rottweil" "")
    (wd:Q8520 "Landkreis Schwäbisch Hall" "deutschland/baden-wuerttemberg/landkreis-schwaebisch-hall" "")
    (wd:Q8203 "Schwarzwald-Baar-Kreis" "deutschland/baden-wuerttemberg/schwarzwald-baar-kreis" "")
    (wd:Q8230 "Landkreis Sigmaringen" "deutschland/baden-wuerttemberg/landkreis-sigmaringen" "")
    (wd:Q1022 "Stuttgart" "deutschland/baden-wuerttemberg/stuttgart" "")
    (wd:Q8214 "Landkreis Tübingen" "deutschland/baden-wuerttemberg/landkreis-tuebingen" "")
    (wd:Q8208 "Landkreis Tuttlingen" "deutschland/baden-wuerttemberg/landkreis-tuttlingen" "")
    (wd:Q3012 "Ulm" "deutschland/baden-wuerttemberg/ulm" "")
    (wd:Q8200 "Landkreis Waldshut" "deutschland/baden-wuerttemberg/landkreis-waldshut" "")
    (wd:Q8233 "Zollernalbkreis" "deutschland/baden-wuerttemberg/zollernalbkreis" "")
	}
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" . }
}