#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Deutschland mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number) {
    (wd:Q980 "Bayern" "deutschland/bayern" "")
        (wd:Q10415 "Landkreis Aichach-Friedberg" "deutschland/bayern/landkreis-aichach-friedberg" "")
        (wd:Q10533 "Landkreis Altötting" "deutschland/bayern/landkreis-altoetting" "")
        (wd:Q7042 "Amberg" "deutschland/bayern/amberg" "")
        (wd:Q10421 "Landkreis Amberg-Sulzbach" "deutschland/bayern/landkreis-amberg-sulzbach" "")
        (wd:Q14859 "Ansbach" "deutschland/bayern/ansbach" "")
        (wd:Q10454 "Landkreis Ansbach" "deutschland/bayern/landkreis-ansbach" "")
        (wd:Q3942 "Aschaffenburg" "deutschland/bayern/aschaffenburg" "")
        (wd:Q10471 "Landkreis Aschaffenburg" "deutschland/bayern/landkreis-aschaffenburg" "")
        (wd:Q2749 "Augsburg" "deutschland/bayern/augsburg" "")
        (wd:Q10414 "Landkreis Augsburg" "deutschland/bayern/landkreis-augsburg" "")
        (wd:Q10466 "Landkreis Bad Kissingen" "deutschland/bayern/landkreis-bad-kissingen" "")
        (wd:Q10522 "Landkreis Bad Tölz-Wolfratshausen" "deutschland/bayern/landkreis-bad-toelz-wolfratshausen" "")
        (wd:Q3936 "Bamberg" "deutschland/bayern/bamberg" "")
        (wd:Q10444 "Landkreis Bamberg" "deutschland/bayern/landkreis-bamberg" "")
        (wd:Q3923 "Bayreuth" "deutschland/bayern/bayreuth" "")
        (wd:Q10439 "Landkreis Bayreuth" "deutschland/bayern/landkreis-bayreuth" "")
        (wd:Q10530 "Landkreis Berchtesgadener Land" "deutschland/bayern/landkreis-berchtesgadener-land" "")
        (wd:Q10424 "Landkreis Cham" "deutschland/bayern/landkreis-cham" "")
        (wd:Q14821 "Coburg" "deutschland/bayern/coburg" "")
        (wd:Q10440 "Landkreis Coburg" "deutschland/bayern/landkreis-coburg" "")
        (wd:Q10500 "Landkreis Dachau" "deutschland/bayern/landkreis-dachau" "")
        (wd:Q10485 "Landkreis Deggendorf" "deutschland/bayern/landkreis-deggendorf" "")
        (wd:Q10417 "Landkreis Dillingen an der Donau" "deutschland/bayern/landkreis-dillingen-an-der-donau" "")
        (wd:Q10480 "Landkreis Dingolfing-Landau" "deutschland/bayern/landkreis-dingolfing-landau" "")
        (wd:Q10418 "Landkreis Donau-Ries" "deutschland/bayern/landkreis-donau-ries" "")
        (wd:Q10541 "Landkreis Ebersberg" "deutschland/bayern/landkreis-ebersberg" "")
        (wd:Q10491 "Landkreis Eichstätt" "deutschland/bayern/landkreis-eichstaett" "")
        (wd:Q10539 "Landkreis Erding" "deutschland/bayern/landkreis-erding" "")
        (wd:Q3126 "Erlangen" "deutschland/bayern/erlangen" "")
        (wd:Q10447 "Landkreis Erlangen-Höchstadt" "deutschland/bayern/landkreis-erlangen-hoechstadt" "")
        (wd:Q10445 "Landkreis Forchheim" "deutschland/bayern/landkreis-forchheim" "")
        (wd:Q10497 "Landkreis Freising" "deutschland/bayern/landkreis-freising" "")
        (wd:Q10487 "Landkreis Freyung-Grafenau" "deutschland/bayern/landkreis-freyung-grafenau" "")
        (wd:Q10502 "Landkreis Fürstenfeldbruck" "deutschland/bayern/landkreis-fuerstenfeldbruck" "")
        (wd:Q3075 "Fürth" "deutschland/bayern/fuerth" "")
            # (wd: "" "deutschland/bayern/fuerth/" "") https://www.fuerthwiki.de/wiki/index.php?title=Stadtteile#Stadtbezirke
        (wd:Q10455 "Landkreis Fürth" "deutschland/bayern/landkreis-fuerth" "")
        (wd:Q10518 "Landkreis Garmisch-Partenkirchen" "deutschland/bayern/landkreis-garmisch-partenkirchen" "")
        (wd:Q10412 "Landkreis Günzburg" "deutschland/bayern/landkreis-guenzburg" "")
        (wd:Q10462 "Landkreis Haßberge" "deutschland/bayern/landkreis-hassberge" "")
        (wd:Q6938 "Hof (Saale)" "deutschland/bayern/hof-saale" "")
        (wd:Q10431 "Landkreis Hof" "deutschland/bayern/landkreis-hof" "")
        (wd:Q3004 "Ingolstadt" "deutschland/bayern/ingolstadt" "")
            # (wd: "" "deutschland/bayern/ingolstadt/" "") https://de.wikipedia.org/wiki/Liste_der_Stadtbezirke_von_Ingolstadt
        (wd:Q14805 "Kaufbeuren" "deutschland/bayern/kaufbeuren" "")
        (wd:Q10474 "Landkreis Kelheim" "deutschland/bayern/landkreis-kelheim" "")
        (wd:Q3994 "Kempten (Allgäu)" "deutschland/bayern/kempten-allgaeu" "")
        (wd:Q10459 "Landkreis Kitzingen" "deutschland/bayern/landkreis-kitzingen" "")
        (wd:Q10434 "Landkreis Kronach" "deutschland/bayern/landkreis-kronach" "")
        (wd:Q10436 "Landkreis Kulmbach" "deutschland/bayern/landkreis-kulmbach" "")
        (wd:Q10507 "Landkreis Landsberg am Lech" "deutschland/bayern/landkreis-landsberg-am-lech" "")
        (wd:Q3974 "Landshut" "deutschland/bayern/landshut" "")
        (wd:Q10475 "Landkreis Landshut" "deutschland/bayern/landkreis-landshut" "")
        (wd:Q10442 "Landkreis Lichtenfels" "deutschland/bayern/landkreis-lichtenfels" "")
        (wd:Q10401 "Landkreis Lindau (Bodensee)" "deutschland/bayern/landkreis-lindau-bodensee" "")
        (wd:Q10469 "Landkreis Main-Spessart" "deutschland/bayern/landkreis-main-spessart" "")
        (wd:Q14825 "Memmingen" "deutschland/bayern/memmingen" "")
        (wd:Q10523 "Landkreis Miesbach" "deutschland/bayern/landkreis-miesbach" "")
        (wd:Q10472 "Landkreis Miltenberg" "deutschland/bayern/landkreis-miltenberg" "")
        (wd:Q10537 "Landkreis Mühldorf am Inn" "deutschland/bayern/landkreis-muehldorf-am-inn" "")
        (wd:Q1726 "München" "deutschland/bayern/muenchen" "")
            (wd:Q971198 "Altstadt-Lehel" "deutschland/bayern/muenchen/altstadt-lehel" "")
            (wd:Q537044 "Ludwigsvorstadt-Isarvorstadt" "deutschland/bayern/muenchen/ludwigsvorstadt-isarvorstadt" "")
            (wd:Q256012 "Maxvorstadt" "deutschland/bayern/muenchen/maxvorstadt" "")
            (wd:Q252910 "Schwabing-West" "deutschland/bayern/muenchen/schwabing-west" "")
            (wd:Q252058 "Au-Haidhausen" "deutschland/bayern/muenchen/au-haidhausen" "")
            (wd:Q262879 "Sendling" "deutschland/bayern/muenchen/sendling" "")
            (wd:Q224635 "Sendling-Westpark" "deutschland/bayern/muenchen/sendling-westpark" "")
            (wd:Q166011 "Schwanthalerhöhe" "deutschland/bayern/muenchen/schwanthalerhoehe" "")
            (wd:Q266932 "Neuhausen-Nymphenburg" "deutschland/bayern/muenchen/neuhausen-nymphenburg" "")
            (wd:Q263163 "Moosach" "deutschland/bayern/muenchen/moosach" "")
            (wd:Q251311 "Milbertshofen-Am Hart" "deutschland/bayern/muenchen/milbertshofen-am-hart" "")
            (wd:Q252679 "Schwabing-Freimann" "deutschland/bayern/muenchen/schwabing-freimann" "")
            (wd:Q329707 "Bogenhausen" "deutschland/bayern/muenchen/bogenhausen" "")
            (wd:Q533054 "Berg am Laim" "deutschland/bayern/muenchen/berg-am-laim" "")
            (wd:Q538037 "Trudering-Riem" "deutschland/bayern/muenchen/trudering-riem" "")
            (wd:Q255291 "Ramersdorf-Perlach" "deutschland/bayern/muenchen/ramersdorf-perlach" "")
            (wd:Q254178 "Obergiesing-Fasangarten" "deutschland/bayern/muenchen/obergiesing-fasangarten" "")
            (wd:Q265068 "Untergiesing-Harlaching" "deutschland/bayern/muenchen/untergiesing-harlaching" "")
            (wd:Q458136 "Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln" "deutschland/bayern/muenchen/thalkirchen-obersendling-forstenried-fuerstenried-solln" "")
            (wd:Q267364 "Hadern" "deutschland/bayern/muenchen/hadern" "")
            (wd:Q255702 "Pasing-Obermenzing" "deutschland/bayern/muenchen/pasing-obermenzing" "")
            (wd:Q533095 "Aubing-Lochhausen-Langwied" "deutschland/bayern/muenchen/aubing-lochhausen-langwied" "")
            (wd:Q252295 "Allach-Untermenzing" "deutschland/bayern/muenchen/allach-untermenzing" "")
            (wd:Q252173 "Feldmoching-Hasenbergl" "deutschland/bayern/muenchen/feldmoching-hasenbergl" "")
            (wd:Q259879 "Laim" "deutschland/bayern/muenchen/laim" "")
        (wd:Q10544 "Landkreis München" "deutschland/bayern/landkreis-muenchen" "")
        (wd:Q10493 "Landkreis Neuburg-Schrobenhausen" "deutschland/bayern/landkreis-neuburg-schrobenhausen" "")
        (wd:Q10427 "Landkreis Neumarkt in der Oberpfalz" "deutschland/bayern/landkreis-neumarkt-in-der-oberpfalz" "")
        (wd:Q10456 "Landkreis Neustadt an der Aisch-Bad Windsheim" "deutschland/bayern/landkreis-neustadt-an-der-aisch-bad-windsheim" "")
        (wd:Q10420 "Landkreis Neustadt an der Waldnaab" "deutschland/bayern/landkreis-neustadt-an-der-waldnaab" "")
        (wd:Q10410 "Landkreis Neu-Ulm" "deutschland/bayern/landkreis-neu-ulm" "")
        (wd:Q2090 "Nürnberg" "deutschland/bayern/nuernberg" "")
            # (wd: "" "deutschland/bayern/nuernberg/" "") https://de.wikipedia.org/wiki/Statistische_Gliederung_von_Nürnberg
        (wd:Q10449 "Landkreis Nürnberger Land" "deutschland/bayern/landkreis-nuernberger-land" "")
        (wd:Q10402 "Landkreis Oberallgäu" "deutschland/bayern/landkreis-oberallgaeu" "")
        (wd:Q10405 "Landkreis Ostallgäu" "deutschland/bayern/landkreis-ostallgaeu" "")
        (wd:Q4190 "Passau" "deutschland/bayern/passau" "")
        (wd:Q10489 "Landkreis Passau" "deutschland/bayern/landkreis-passau" "")
        (wd:Q10496 "Landkreis Pfaffenhofen an der Ilm" "deutschland/bayern/landkreis-pfaffenhofen-an-der-ilm" "")
        (wd:Q10483 "Landkreis Regen" "deutschland/bayern/landkreis-regen" "")
        (wd:Q2978 "Regensburg" "deutschland/bayern/regensburg" "")
        (wd:Q10429 "Landkreis Regensburg" "deutschland/bayern/landkreis-regensburg" "")
        (wd:Q10465 "Landkreis Rhön-Grabfeld" "deutschland/bayern/landkreis-rhoen-grabfeld" "")
        (wd:Q4007 "Rosenheim" "deutschland/bayern/rosenheim" "")
        (wd:Q10526 "Landkreis Rosenheim" "deutschland/bayern/landkreis-rosenheim" "")
        (wd:Q10451 "Landkreis Roth" "deutschland/bayern/landkreis-roth" "")
        (wd:Q10477 "Landkreis Rottal-Inn" "deutschland/bayern/landkreis-rottal-inn" "")
        (wd:Q14889 "Schwabach" "deutschland/bayern/schwabach" "")
        (wd:Q10423 "Landkreis Schwandorf" "deutschland/bayern/landkreis-schwandorf" "")
        (wd:Q4126 "Schweinfurt" "deutschland/bayern/schweinfurt" "")
        (wd:Q10461 "Landkreis Schweinfurt" "deutschland/bayern/landkreis-schweinfurt" "")
        (wd:Q10504 "Landkreis Starnberg" "deutschland/bayern/landkreis-starnberg" "")
        (wd:Q7027 "Straubing" "deutschland/bayern/straubing" "")
        (wd:Q10482 "Landkreis Straubing-Bogen" "deutschland/bayern/landkreis-straubing-bogen" "")
        (wd:Q10419 "Landkreis Tirschenreuth" "deutschland/bayern/landkreis-tirschenreuth" "")
        (wd:Q10528 "Landkreis Traunstein" "deutschland/bayern/landkreis-traunstein" "")
        (wd:Q10408 "Landkreis Unterallgäu" "deutschland/bayern/landkreis-unterallgaeu" "")
        (wd:Q14803 "Weiden in der Oberpfalz" "deutschland/bayern/weiden-in-der-oberpfalz" "")
        (wd:Q10516 "Landkreis Weilheim-Schongau" "deutschland/bayern/landkreis-weilheim-schongau" "")
        (wd:Q10453 "Landkreis Weißenburg-Gunzenhausen" "deutschland/bayern/landkreis-weissenburg-gunzenhausen" "")
        (wd:Q10432 "Landkreis Wunsiedel im Fichtelgebirge" "deutschland/bayern/landkreis-wunsiedel-im-fichtelgebirge" "")
        (wd:Q2999 "Würzburg" "deutschland/bayern/wuerzburg" "")
            # (wd: "" "deutschland/bayern/wuerzburg/" "") https://de.wikipedia.org/wiki/Liste_der_Stadtbezirke_Würzburgs
        (wd:Q10458 "Landkreis Würzburg" "deutschland/bayern/landkreis-wuerzburg" "")
		}
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label {
	bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" .
  }
}