#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Berlin mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape ?number ?rgb
WHERE 
{
  VALUES (?id ?name ?safeURL ?number) 
  {
    (wd:Q163966 "Mitte" "deutschland/berlin/mitte" "")
    (wd:Q158893 "Friedrichshain-Kreuzberg" "deutschland/berlin/friedrichshain-kreuzberg" "")
    (wd:Q163012 "Pankow" "deutschland/berlin/pankow" "")
    (wd:Q158095 "Charlottenburg-Wilmersdorf" "deutschland/berlin/charlottenburg-wilmersdorf" "")
    (wd:Q158083 "Spandau" "deutschland/berlin/spandau" "")
    (wd:Q158064 "Steglitz-Zehlendorf" "deutschland/berlin/steglitz-zehlendorf" "")
    (wd:Q158106 "Tempelhof-Schöneberg" "deutschland/berlin/tempelhof-schoeneberg" "")
    (wd:Q4071168 "Neukölln" "deutschland/berlin/neukoelln" "")
    (wd:Q158089 "Treptow-Köpenick" "deutschland/berlin/treptow-koepenick" "")
    (wd:Q119284 "Marzahn-Hellersdorf" "deutschland/berlin/marzahn-hellersdorf" "")
    (wd:Q329609 "Lichtenberg" "deutschland/berlin/lichtenberg" "")
    (wd:Q158876 "Reinickendorf" "deutschland/berlin/reinickendorf" "")
	}
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" . }
}