#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Nordrhein-Westfalen mit Anzahl der erfassten Stolpersteine
# Anzahl der Stolpersteine Stand 22. August 2025
SELECT ?id ?name ?geoshape ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number) {
    # (wd:Q1198 "Nordrhein-Westfalen" "deutschland/nordrhein-westfalen" "") 
        # (wd:Q6272 "Städteregion Aachen" "deutschland/nordrhein-westfalen/staedteregion-aachen" "23")
          # (wd:Q1017 "Aachen" "deutschland/nordrhein-westfalen/staedteregion-aachen/aachen" "1") 
            (wd:Q300703 "Aachen-Mitte" "deutschland/nordrhein-westfalen/staedteregion-aachen/aachen/aachen-mitte" "1")
            (wd:Q151287 "Brand" "deutschland/nordrhein-westfalen/staedteregion-aachen/aachen/brand" "0")
            (wd:Q1304021 "Eilendorf" "deutschland/nordrhein-westfalen/staedteregion-aachen/aachen/eilendorf" "0")
            (wd:Q1566490 "Haaren" "deutschland/nordrhein-westfalen/staedteregion-aachen/aachen/haaren" "0")
            (wd:Q2563710 "Kornelimünster/Walheim" "deutschland/nordrhein-westfalen/staedteregion-aachen/aachen/kornelimuenster-walheim" "0")
            (wd:Q1808050 "Laurensberg" "deutschland/nordrhein-westfalen/staedteregion-aachen/aachen/laurensberg" "0")
            (wd:Q2151315 "Richterich" "deutschland/nordrhein-westfalen/staedteregion-aachen/aachen/richterich" "0")
          (wd:Q6992 "Alsdorf" "deutschland/nordrhein-westfalen/staedteregion-aachen/alsdorf" "0") 
          (wd:Q200894 "Baesweiler" "deutschland/nordrhein-westfalen/staedteregion-aachen/baesweiler" "14") 
          (wd:Q4083 "Eschweiler" "deutschland/nordrhein-westfalen/staedteregion-aachen/eschweiler" "0") 
          (wd:Q6916 "Herzogenrath" "deutschland/nordrhein-westfalen/staedteregion-aachen/herzogenrath" "0") 
          (wd:Q200783 "Monschau" "deutschland/nordrhein-westfalen/staedteregion-aachen/monschau" "5") 
          (wd:Q200743 "Roetgen" "deutschland/nordrhein-westfalen/staedteregion-aachen/gemeinde-roetgen" "2") 
          (wd:Q200836 "Simmerath" "deutschland/nordrhein-westfalen/staedteregion-aachen/gemeinde-simmerath" "0") 
          (wd:Q4068 "Stolberg" "deutschland/nordrhein-westfalen/staedteregion-aachen/stolberg" "0") 
          (wd:Q14901 "Würselen" "deutschland/nordrhein-westfalen/staedteregion-aachen/wuerselen" "1") 
        # (wd:Q2112 "Bielefeld" "deutschland/nordrhein-westfalen/bielefeld" "3")
          (wd:Q857314 "Mitte" "deutschland/nordrhein-westfalen/bielefeld/mitte" "")
          (wd:Q59138732 "Schildesche" "deutschland/nordrhein-westfalen/bielefeld/schildesche" "")
          (wd:Q1490832 "Gadderbaum" "deutschland/nordrhein-westfalen/bielefeld/gadderbaum" "")
          (wd:Q59138211 "Brackwede" "deutschland/nordrhein-westfalen/bielefeld/brackwede" "")
          (wd:Q884493 "Dornberg" "deutschland/nordrhein-westfalen/bielefeld/dornberg" "")
          (wd:Q59138453 "Jöllenbeck" "deutschland/nordrhein-westfalen/bielefeld/joellenbeck" "")
          (wd:Q59138276 "Heepen" "deutschland/nordrhein-westfalen/bielefeld/heepen" "")
          (wd:Q59139024 "Stieghorst" "deutschland/nordrhein-westfalen/bielefeld/stieghorst" "")
          (wd:Q59138834 "Sennestadt" "deutschland/nordrhein-westfalen/bielefeld/sennestadt" "")
          (wd:Q1457938 "Senne" "deutschland/nordrhein-westfalen/bielefeld/senne" "")    
        # (wd:Q2103 "Bochum" "deutschland/nordrhein-westfalen/bochum" "391")
          (wd:Q2662781 "Mitte" "deutschland/nordrhein-westfalen/bochum/mitte" "")
          (wd:Q492224 "Wattenscheid" "deutschland/nordrhein-westfalen/bochum/wattenscheid" "")
          (wd:Q27973169 "Nord" "deutschland/nordrhein-westfalen/bochum/nord" "")
          (wd:Q23788002 "Ost" "deutschland/nordrhein-westfalen/bochum/ost" "")
          (wd:Q3641512 "Süd" "deutschland/nordrhein-westfalen/bochum/sued" "")
          (wd:Q27973016 "Südwest" "deutschland/nordrhein-westfalen/bochum/suedwest" "")
        # (wd:Q586 "Bonn" "deutschland/nordrhein-westfalen/bonn" "2")
          (wd:Q153260 "Bad Godesberg" "deutschland/nordrhein-westfalen/bonn/bad-godesberg" "")
          (wd:Q153745 "Beuel" "deutschland/nordrhein-westfalen/bonn/beuel" "")
          (wd:Q892684 "Bonn" "deutschland/nordrhein-westfalen/bonn/bonn" "")
          (wd:Q450087 "Hardtberg" "deutschland/nordrhein-westfalen/bonn/hardtberg" "")
        (wd:Q6191 "Kreis Borken" "deutschland/nordrhein-westfalen/kreis-borken" "170")
        (wd:Q3069 "Bottrop" "deutschland/nordrhein-westfalen/bottrop" "12")
          # (wd:Q59139715 "Mitte" "deutschland/nordrhein-westfalen/bottrop/mitte" "") # P3896 fehlt
          # (wd:Q59139867 "Süd" "deutschland/nordrhein-westfalen/bottrop/sued" "") # P3896 fehlt
          # (wd:Q314047 "Kirchhellen" "deutschland/nordrhein-westfalen/bottrop/kirchhellen" "") # P3896 fehlt
        (wd:Q6210 "Kreis Coesfeld" "deutschland/nordrhein-westfalen/kreis-coesfeld" "133")
        # (wd:Q1295 "Dortmund" "deutschland/nordrhein-westfalen/dortmund" "1")
          (wd:Q2326757 "Innenstadt-West" "deutschland/nordrhein-westfalen/dortmund/innenstadt-west" "")
          (wd:Q2326748 "Innenstadt-Nord" "deutschland/nordrhein-westfalen/dortmund/innenstadt-nord" "")
          (wd:Q2326752 "Innenstadt-Ost" "deutschland/nordrhein-westfalen/dortmund/innenstadt-ost" "")
          (wd:Q989822 "Eving" "deutschland/nordrhein-westfalen/dortmund/eving" "")
          (wd:Q2326759 "Scharnhorst" "deutschland/nordrhein-westfalen/dortmund/scharnhorst" "")
          (wd:Q2326741 "Brackel" "deutschland/nordrhein-westfalen/dortmund/brackel" "")
          (wd:Q1168004 "Aplerbeck" "deutschland/nordrhein-westfalen/dortmund/aplerbeck" "")
          (wd:Q2024532 "Hörde" "deutschland/nordrhein-westfalen/dortmund/hoerde" "")
          (wd:Q1250639 "Hombruch" "deutschland/nordrhein-westfalen/dortmund/hombruch" "")
          (wd:Q1554715 "Lütgendortmund" "deutschland/nordrhein-westfalen/dortmund/luetgendortmund" "")
          (wd:Q2326745 "Huckarde" "deutschland/nordrhein-westfalen/dortmund/huckarde" "")
          (wd:Q1369141 "Mengede" "deutschland/nordrhein-westfalen/dortmund/mengede" "")
        # (wd:Q2100 "Duisburg" "deutschland/nordrhein-westfalen/duisburg" "3")
          (wd:Q449632 "Walsum" "deutschland/nordrhein-westfalen/duisburg/walsum" "")
          (wd:Q512233 "Hamborn" "deutschland/nordrhein-westfalen/duisburg/hamborn" "")
          (wd:Q5764545 "Meiderich/Beeck" "deutschland/nordrhein-westfalen/duisburg/meiderich-beeck" "")
          (wd:Q881325 "Homberg/Ruhrort/Baerl" "deutschland/nordrhein-westfalen/duisburg/homberg-ruhrort-baerl" "")
          (wd:Q317314 "Mitte" "deutschland/nordrhein-westfalen/duisburg/mitte" "")
          (wd:Q469928 "Rheinhausen" "deutschland/nordrhein-westfalen/duisburg/rheinhausen" "")
          (wd:Q884445 "Süd" "deutschland/nordrhein-westfalen/duisburg/sued" "")
        (wd:Q6275 "Kreis Düren" "deutschland/nordrhein-westfalen/kreis-dueren" "0")
        # (wd:Q1718 "Düsseldorf" "deutschland/nordrhein-westfalen/duesseldorf" "311")
          (wd:Q551600 "Stadtbezirk 1" "deutschland/nordrhein-westfalen/duesseldorf/stadtbezirk-1" "")
          (wd:Q320896 "Stadtbezirk 2" "deutschland/nordrhein-westfalen/duesseldorf/stadtbezirk-2" "")
          (wd:Q322875 "Stadtbezirk 3" "deutschland/nordrhein-westfalen/-uesseldorf/stadtbezirk-3" "")
          (wd:Q323607 "Stadtbezirk 4" "deutschland/nordrhein-westfalen/duesseldorf/stadtbezirk-4" "")
          (wd:Q323588 "Stadtbezirk 5" "deutschland/nordrhein-westfalen/duesseldorf/stadtbezirk-5" "")
          (wd:Q831039 "Stadtbezirk 6" "deutschland/nordrhein-westfalen/duesseldorf/stadtbezirk-6" "")
          (wd:Q323826 "Stadtbezirk 7" "deutschland/nordrhein-westfalen/duesseldorf/stadtbezirk-7" "")
          (wd:Q870865 "Stadtbezirk 8" "deutschland/nordrhein-westfalen/duesseldorf/stadtbezirk-8" "")
          (wd:Q323577 "Stadtbezirk 9" "deutschland/nordrhein-westfalen/duesseldorf/stadtbezirk-9" "")
          (wd:Q831067 "Stadtbezirk 10" "deutschland/nordrhein-westfalen/duesseldorf/stadtbezirk-10" "")
        (wd:Q11280 "Ennepe-Ruhr-Kreis" "deutschland/nordrhein-westfalen/ennepe-ruhr-kreis" "109")
        # (wd:Q2066 "Essen" "deutschland/nordrhein-westfalen/essen" "6")
          (wd:Q54803595 "Stadtmitte/Frillendorf/Huttrop" "deutschland/nordrhein-westfalen/essen/stadtmitte-frillendorf-huttrop" "")
          (wd:Q54803598 "Rüttenscheid/Bergerhausen/Rellinghausen" "deutschland/nordrhein-westfalen/essen/ruettenscheid-bergerhausen-rellinghausen" "")
          (wd:Q54803599 "West" "deutschland/nordrhein-westfalen/essen/west" "")
          (wd:Q54803600 "Borbeck" "deutschland/nordrhein-westfalen/essen/borbeck" "")
          (wd:Q54803601 "Altenessen/Karnap/Vogelheim" "deutschland/nordrhein-westfalen/essen/altenessen-karnap-vogelheim" "")
          (wd:Q54803602 "Zollverein" "deutschland/nordrhein-westfalen/essen/zollverein" "")
          (wd:Q54803603 "Steele/Kray" "deutschland/nordrhein-westfalen/essen/steele-kray" "")
          (wd:Q54803604 "Ruhrhalbinsel" "deutschland/nordrhein-westfalen/essen/ruhrhalbinsel" "")
          (wd:Q14208738 "Werden/Kettwig/Bredeney" "deutschland/nordrhein-westfalen/essen/werden-kettwig-bredeney" "")
        (wd:Q6280 "Kreis Euskirchen" "deutschland/nordrhein-westfalen/kreis-euskirchen" "20")
        # (wd:Q2765 "Gelsenkirchen" "deutschland/nordrhein-westfalen/gelsenkirchen" "4")
          (wd:Q59140253 "Nord" "deutschland/nordrhein-westfalen/gelsenkirchen/nord" "")
          (wd:Q59140358 "Ost" "deutschland/nordrhein-westfalen/gelsenkirchen/ost" "")
          (wd:Q59140331 "West" "deutschland/nordrhein-westfalen/gelsenkirchen/west" "")
          (wd:Q59140275 "Mitte" "deutschland/nordrhein-westfalen/gelsenkirchen/mitte" "")
          (wd:Q59140398 "Süd" "deutschland/nordrhein-westfalen/gelsenkirchen/sued" "")
        (wd:Q6218 "Kreis Gütersloh" "deutschland/nordrhein-westfalen/kreis-guetersloh" "1")
        # (wd:Q2871 "Hagen" "deutschland/nordrhein-westfalen/hagen" "0")
          (wd:Q59240322 "Mitte" "deutschland/nordrhein-westfalen/hagen/mitte" "")
          (wd:Q59240473 "Nord" "deutschland/nordrhein-westfalen/hagen/nord" "")
          (wd:Q27994630 "Haspe" "deutschland/nordrhein-westfalen/hagen/haspe" "") #P3896 unklar
          (wd:Q1304125 "Eilpe/Dahl" "deutschland/nordrhein-westfalen/hagen/eilpe-dahl" "")
          (wd:Q59241193 "Hohenlimburg" "deutschland/nordrhein-westfalen/hagen/hohenlimburg" "")
        (wd:Q2880 "Hamm" "deutschland/nordrhein-westfalen/hamm" "2")
        (wd:Q6264 "Kreis Heinsberg" "deutschland/nordrhein-westfalen/kreis-heinsberg" "11")
        (wd:Q6234 "Kreis Herford" "deutschland/nordrhein-westfalen/kreis-herford" "1")
        # (wd:Q2904 "Herne" "deutschland/nordrhein-westfalen/herne" "0")
          (wd:Q23758642 "Wanne" "deutschland/nordrhein-westfalen/herne/wanne" "")
          (wd:Q20183677 "Eickel" "deutschland/nordrhein-westfalen/herne/eickel" "")
          (wd:Q25392878 "Mitte" "deutschland/nordrhein-westfalen/herne/mitte" "")
          (wd:Q15114696 "Sodingen" "deutschland/nordrhein-westfalen/herne/sodingen" "")
        (wd:Q5946 "Hochsauerlandkreis" "deutschland/nordrhein-westfalen/hochsauerlandkreis" "15")
        (wd:Q6228 "Kreis Höxter" "deutschland/nordrhein-westfalen/kreis-hoexter" "2")
        (wd:Q6246 "Kreis Kleve" "deutschland/nordrhein-westfalen/kreis-kleve" "243")
        # (wd:Q365 "Köln" "deutschland/nordrhein-westfalen/koeln" "69")
          (wd:Q446857 "Innenstadt" "deutschland/nordrhein-westfalen/koeln/innenstadt" "")
          (wd:Q446716 "Rodenkirchen" "deutschland/nordrhein-westfalen/koeln/rodenkirchen" "")
          (wd:Q518491 "Lindenthal" "deutschland/nordrhein-westfalen/koeln/lindenthal" "")
          (wd:Q458126 "Ehrenfeld" "deutschland/nordrhein-westfalen/koeln/ehrenfeld" "")
          (wd:Q518604 "Nippes" "deutschland/nordrhein-westfalen/koeln/nippes" "")
          (wd:Q446864 "Chorweiler" "deutschland/nordrhein-westfalen/koeln/chorweiler" "")
          (wd:Q458242 "Porz" "deutschland/nordrhein-westfalen/koeln/porz" "")
          (wd:Q446870 "Kalk" "deutschland/nordrhein-westfalen/koeln/kalk" "")
          (wd:Q153779 "Mülheim" "deutschland/nordrhein-westfalen/koeln/muelheim" "")
        (wd:Q2805 "Krefeld" "deutschland/nordrhein-westfalen/krefeld" "3") # Die Einteilung der Stadtbezirke ist noch unklar
			  (wd:Q2938 "Leverkusen" "deutschland/nordrhein-westfalen/leverkusen" "0") # Die Einteilung der Stadtbezirke ist noch unklar
        (wd:Q6230 "Kreis Lippe" "deutschland/nordrhein-westfalen/kreis-lippe" "0")
        (wd:Q5937 "Märkischer Kreis" "deutschland/nordrhein-westfalen/maerkischer-kreis" "2")
        (wd:Q6257 "Kreis Mettmann" "deutschland/nordrhein-westfalen/kreis-mettmann" "2")
        (wd:Q6239 "Kreis Minden-Lübbecke" "deutschland/nordrhein-westfalen/kreis-minden-luebbecke" "0")
        # (wd:Q2758 "Mönchengladbach" "deutschland/nordrhein-westfalen/moenchengladbach" "1")
          (wd:Q30401 "Nord" "deutschland/nordrhein-westfalen/moenchengladbach/nord" "")
          (wd:Q30403 "Ost" "deutschland/nordrhein-westfalen/moenchengladbach/ost" "")
          (wd:Q30399 "Süd" "deutschland/nordrhein-westfalen/moenchengladbach/sued" "")
          (wd:Q30392 "West" "deutschland/nordrhein-westfalen/moenchengladbach/west" "")
        # (wd:Q2899 "Mülheim an der Ruhr" "deutschland/nordrhein-westfalen/muelheim-an-der-ruhr" "6")
          (wd:Q121366237 "Rechtsruhr-Süd" "deutschland/nordrhein-westfalen/muelheim-an-der-ruhr/rechtsruhr-sued" "")
          (wd:Q121362842 "Rechtsruhr-Nord" "deutschland/nordrhein-westfalen/muelheim-an-der-ruhr/rechtsruhr-nord" "")
          (wd:Q121879491 "Linksruhr" "deutschland/nordrhein-westfalen/muelheim-an-der-ruhr/linksruhr" "")
        # (wd:Q2742 "Münster" "deutschland/nordrhein-westfalen/muenster" "70")
          (wd:Q1959104 "Mitte" "deutschland/nordrhein-westfalen/muenster/mitte" "")
          (wd:Q1761685 "Nord" "deutschland/nordrhein-westfalen/muenster/nord" "")
          (wd:Q1503134 "Ost" "deutschland/nordrhein-westfalen/muenster/ost" "")
          (wd:Q1318888 "West" "deutschland/nordrhein-westfalen/muenster/west" "")
          (wd:Q1959115 "Süd-Ost" "deutschland/nordrhein-westfalen/muenster/sued-ost" "")
          (wd:Q59207767 "Hiltrup" "deutschland/nordrhein-westfalen/muenster/hiltrup" "")
        (wd:Q6298 "Oberbergischer Kreis" "deutschland/nordrhein-westfalen/oberbergischer-kreis" "0")
        # (wd:Q2838 "Oberhausen" "deutschland/nordrhein-westfalen/oberhausen" "1")
          (wd:Q432964 "Alt-Oberhausen" "deutschland/nordrhein-westfalen/oberhausen/alt-oberhausen" "")
          (wd:Q883208 "Sterkrade" "deutschland/nordrhein-westfalen/oberhausen/sterkrade" "")
          (wd:Q2035183 "Osterfeld" "deutschland/nordrhein-westfalen/oberhausen/osterfeld" "")
        (wd:Q5953 "Kreis Olpe" "deutschland/nordrhein-westfalen/kreis-olpe" "0")
        (wd:Q6224 "Kreis Paderborn" "deutschland/nordrhein-westfalen/kreis-paderborn" "40")
        (wd:Q6214 "Kreis Recklinghausen" "deutschland/nordrhein-westfalen/kreis-recklinghausen" "30")
        (wd:Q3097 "Remscheid" "deutschland/nordrhein-westfalen/remscheid" "1")
        (wd:Q6292 "Rhein-Erft-Kreis" "deutschland/nordrhein-westfalen/rhein-erft-kreis" "2")
        (wd:Q6295 "Rheinisch-Bergischer Kreis" "deutschland/nordrhein-westfalen/rheinisch-bergischer-kreis" "1")
        (wd:Q6253 "Rhein-Kreis Neuss" "deutschland/nordrhein-westfalen/rhein-kreis-neuss" "0")
        (wd:Q6287 "Rhein-Sieg-Kreis" "deutschland/nordrhein-westfalen/rhein-sieg-kreis" "0")
        (wd:Q5982 "Kreis Siegen-Wittgenstein" "deutschland/nordrhein-westfalen/kreis-siegen-wittgenstein" "1")
        (wd:Q5965 "Kreis Soest" "deutschland/nordrhein-westfalen/kreis-soest" "9")
        (wd:Q2942 "Solingen" "deutschland/nordrhein-westfalen/solingen" "12")
        (wd:Q6187 "Kreis Steinfurt" "deutschland/nordrhein-westfalen/kreis-steinfurt" "55")
        (wd:Q6163 "Kreis Unna" "deutschland/nordrhein-westfalen/kreis-unna" "11")
        (wd:Q6249 "Kreis Viersen" "deutschland/nordrhein-westfalen/kreis-viersen" "26")
        (wd:Q2839 "Kreis Warendorf" "deutschland/nordrhein-westfalen/kreis-warendorf" "353")
        (wd:Q6245 "Kreis Wesel" "deutschland/nordrhein-westfalen/kreis-wesel" "14")
        # (wd:Q2107 "Wuppertal" "deutschland/nordrhein-westfalen/wuppertal" "187")
          (wd:Q1325222 "Elberfeld" "deutschland/nordrhein-westfalen/wuppertal/elberfeld" "")
          (wd:Q1325224 "Elberfeld-West" "deutschland/nordrhein-westfalen/wuppertal/elberfeld-west" "")
          (wd:Q1719793 "Uellendahl-Katernberg" "deutschland/nordrhein-westfalen/wuppertal/uellendahl-katernberg" "")
          (wd:Q314456 "Vohwinkel" "deutschland/nordrhein-westfalen/wuppertal/vohwinkel" "")
          (wd:Q769183 "Cronenberg" "deutschland/nordrhein-westfalen/wuppertal/cronenberg" "")
          (wd:Q13388983 "Barmen" "deutschland/nordrhein-westfalen/wuppertal/barmen" "")
          (wd:Q2009133 "Oberbarmen" "deutschland/nordrhein-westfalen/wuppertal/oberbarmen" "")
          (wd:Q1232709 "Heckinghausen" "deutschland/nordrhein-westfalen/wuppertal/heckinghausen" "") # P3896 fehlt
          (wd:Q114402 "Langerfeld-Beyenburg" "deutschland/nordrhein-westfalen/wuppertal/langerfeld-beyenburg" "")
          (wd:Q681425 "Ronsdorf" "deutschland/nordrhein-westfalen/wuppertal/ronsdorf" "")
		}
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label {
	bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" .
  }
}
