#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Sachsen mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number)
  {
    (wd:Q571947 "Landkreis Bautzen" "deutschland/sachsen/landkreis-bautzen" "")
    (wd:Q2795 "Chemnitz" "deutschland/sachsen/chemnitz" "")
    (wd:Q1731 "Dresden" "deutschland/sachsen/dresden" "")
    (wd:Q6339 "Erzgebirgskreis" "deutschland/sachsen/erzgebirgskreis" "")
    (wd:Q6317 "Landkreis Görlitz" "deutschland/sachsen/landkreis-goerlitz" "")
    (wd:Q6308 "Landkreis Leipzig" "deutschland/sachsen/landkreis-leipzig" "")
    (wd:Q2079 "Leipzig" "deutschland/sachsen/leipzig" "")
    (wd:Q6313 "Landkreis Meißen" "deutschland/sachsen/landkreis-meissen" "")
    (wd:Q6328 "Landkreis Mittelsachsen" "deutschland/sachsen/landkreis-mittelsachsen" "")
    (wd:Q6301 "Landkreis Nordsachsen" "deutschland/sachsen/landkreis-nordsachsen" "")
    (wd:Q6323 "Landkreis Sächsische Schweiz-Osterzgebirge" "deutschland/sachsen/landkreis-saechsische-schweiz-osterzgebirge" "")
    (wd:Q6337 "Vogtlandkreis" "deutschland/sachsen/vogtlandkreis" "")
    (wd:Q6330 "Landkreis Zwickau" "deutschland/sachsen/landkreis-zwickau" "")
  }
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" . }
}