#defaultView:Map{"hide":["?id", "?safeName", "?rgb", "?geoshape"]}
#title: Karte aller Verwaltungseinheiten in Berlin mit Anzahl der erfassten Stolpersteine
SELECT ?id ?name ?geoshape ?number ?rgb
WHERE {
  VALUES (?id ?name ?safeURL ?number) {
    (wd:Q1205 "Thüringen" "deutschland/thueringen" "")
        (wd:Q7888 "Landkreis Altenburger Land" "deutschland/thueringen/landkreis-altenburger-land" "")
        (wd:Q7861 "Landkreis Eichsfeld" "deutschland/thueringen/landkreis-eichsfeld" "")
        (wd:Q1729 "Erfurt" "deutschland/thueringen/erfurt" "")
        (wd:Q3750 "Gera" "deutschland/thueringen/gera" "")
        (wd:Q7869 "Landkreis Gotha" "deutschland/thueringen/landkreis-gotha" "")
        (wd:Q7887 "Landkreis Greiz" "deutschland/thueringen/landkreis-greiz" "")
        (wd:Q7872 "Landkreis Hildburghausen" "deutschland/thueringen/landkreis-hildburghausen" "")
        (wd:Q7878 "Ilm-Kreis" "deutschland/thueringen/ilm-kreis" "")
        (wd:Q3150 "Jena" "deutschland/thueringen/jena" "")
        (wd:Q7862 "Kyffhäuserkreis" "deutschland/thueringen/landkreis-kyffhaeuserkreis" "")
        (wd:Q7858 "Landkreis Nordhausen" "deutschland/thueringen/landkreis-nordhausen" "")
        (wd:Q7884 "Saale-Holzland-Kreis" "deutschland/thueringen/saale-holzland-kreis" "")
        (wd:Q7883 "Saale-Orla-Kreis" "deutschland/thueringen/saale-orla-kreis" "")
        (wd:Q7882 "Landkreis Saalfeld-Rudolstadt" "deutschland/thueringen/landkreis-saalfeld-rudolstadt" "")
        (wd:Q7871 "Landkreis Schmalkalden-Meiningen" "deutschland/thueringen/landkreis-schmalkalden-meiningen" "")
        (wd:Q7865 "Landkreis Sömmerda" "deutschland/thueringen/landkreis-soemmerda" "")
        (wd:Q7875 "Landkreis Sonneberg" "deutschland/thueringen/landkreis-sonneberg" "")
        (wd:Q14891 "Suhl" "deutschland/thueringen/suhl" "")
        (wd:Q7864 "Unstrut-Hainich-Kreis" "deutschland/thueringen/unstrut-hainich-kreis" "")
        (wd:Q7866 "Wartburgkreis" "deutschland/thueringen/wartburgkreis" "")
        (wd:Q3955 "Weimar" "deutschland/thueringen/weimar" "")
        (wd:Q7879 "Landkreis Weimarer Land" "deutschland/thueringen/landkreis-weimarer-land" "")
		}
  ?id wdt:P3896 ?geoshape .
  BIND (IF(?number > "0","008000","d2042d") AS ?rgb)
  SERVICE wikibase:label {
	bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en" .
  }
}